apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bisheng.fullname" . }}
  labels:
    {{- include "bisheng.labels" . | nindent 4 }}
type: Opaque
stringData:
  gatewayHmacSecret: {{ .Values.secrets.gatewayHmacSecret | quote }}
  minioAccessKey: {{ .Values.middleware.minio.accessKey | quote }}
  minioSecretKey: {{ .Values.middleware.minio.secretKey | quote }}
  {{- if and .Values.sandbox.enabled (not .Values.sandbox.existingSecret) }}
  sandboxToken: {{ .Values.sandbox.token | quote }}
  {{- end }}
