- type: arxiv
  # 1. 用于访问arXiv API的工具
  
- type: bing_search
  # 2. 用于执行Bing搜索的工具
  bing_search_url: https://api.bing.microsoft.com/v7.0/search
  bing_subscription_key: 
  
- type: calculator
  # 3. 用于执行计算的工具
  
- type: bisheng_code_interpreter
  # 4. 用于执行代码的工具
  minio:
    MINIO_ACCESS_KEY: 
    MINIO_SECRET_KEY: 
    CERT_CHECK: false
    MINIO_ENDPOINT: 192.168.106.116:9000
    SCHEMA: false

- type: dalle_image_generator
  # 5. 使用OpenAI的DALL-E模型生成图像的工具
  openai_api_key: 
  openai_proxy:

- type: get_current_time
  # 6. 获取当前时间的工具
  
- type: macro_china_consumer_goods_retail
  # 7. 用于访问中国消费品零售行业的宏观经济数据的工具
  
- type: macro_china_cpi
  # 8. 用于访问中国消费者价格指数（CPI）的宏观经济数据的工具
  
- type: macro_china_gdp_yearly
  # 9. 用于访问中国年度国内生产总值（GDP）的宏观经济数据的工具
  
- type: macro_china_money_supply
  # 10. 用于访问中国货币供应量的宏观经济数据的工具
  
- type: macro_china_ppi
  # 11. 用于访问中国生产者价格指数（PPI）的宏观经济数据的工具
  
- type: macro_china_shrzgm
  # 12. 用于访问中国社会融资规模的宏观经济数据的工具
  
- type: sina_history_KLine
  # 13. 用于访问新浪财经的历史K线数据的工具
  
- type: sina_realtime_info
  # 14. 用于访问新浪财经的实时股票信息的工具
  
- type: tianyancha_all_companys_by_company
  # 15. 使用天眼查API按公司名称搜索所有公司的工具
  api_key: 
  
- type: tianyancha_all_companys_by_humanname
  # 16. 使用天眼查API按人名搜索所有公司的工具
  api_key: 
  
- type: tianyancha_company_change_info
  # 17. 使用天眼查API访问公司变更信息的工具
  api_key: 
  
- type: tianyancha_company_holders
  # 18. 使用天眼查API访问公司股东信息的工具
  api_key: 
  
- type: tianyancha_get_company_baseinfo
  # 19. 使用天眼查API访问公司基本信息的工具
  api_key: 
  
- type: tianyancha_ic_info
  # 20. 使用天眼查API访问公司工商信息的工具
  api_key: 
  
- type: tianyancha_ip_rights
  # 21. 使用天眼查API访问公司知识产权信息的工具
  api_key: 
  
- type: tianyancha_judicial_risk
  # 22. 使用天眼查API访问公司司法风险信息的工具
  api_key: 
  
- type: tianyancha_law_suit_case
  # 23. 使用天眼查API访问公司诉讼案例信息的工具
  api_key: 
  
- type: tianyancha_riskinfo
  # 24. 使用天眼查API访问公司风险信息的工具
  api_key: 
  
- type: tianyancha_search_company
  # 25. 使用天眼查API搜索公司的工具
  api_key:

- type: flow_knowledge_retrieve
  # 26. 知识库检索工具
  collection_id: 699
  description: "美团知识库检索工具，从美团知识库进行检索总结"

- type: macro_china_pmi
  # 27. 用于访问中国采购经理人指数（PMI）的宏观经济数据的工具

- type: bond_zh_us_rate
  # 28. 指定时间段内交易日的中美两国的收益率数据
