"""One-shot generator for scripts/sql/fill_mysql_table_column_comments.sql.

Run from src/backend:
  PYTHONPATH=./ uv run python scripts/_gen_fill_mysql_comments.py
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

_BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

import bisheng
from bisheng.common.models.base import SQLModelSerializable
from sqlmodel import SQLModel

TABLE_COMMENTS: dict[str, str] = {
    "approval_action_log": "审批操作流水",
    "approval_exception": "审批异常记录",
    "approval_flow_definition": "审批流程定义",
    "approval_flow_version": "审批流程版本",
    "approval_instance": "审批实例",
    "approval_node_definition": "审批节点定义",
    "approval_notification_outbox": "审批通知发件箱",
    "approval_outbox": "审批回调发件箱",
    "approval_request": "审批申请单",
    "approval_route_rule": "审批路由规则",
    "approval_scenario": "审批场景",
    "approval_task": "审批任务",
    "assistant": "助手",
    "assistantlink": "助手关联资源",
    "auditlog": "审计日志",
    "channel": "信息频道",
    "channel_article_read": "频道文章已读记录",
    "channel_info_source": "频道信息源",
    "channel_knowledge_sync": "频道知识空间同步配置",
    "chatmessage": "会话消息",
    "config": "系统配置",
    "dashboard": "数据看板",
    "dashboard_component": "看板组件",
    "dashboard_dataset": "看板数据集",
    "dashboard_default": "用户默认看板",
    "dataset": "评测/训练数据集",
    "department": "部门",
    "department_admin_grant": "部门管理员授权",
    "department_file_view_grant": "部门文件查看授权",
    "department_knowledge_space": "部门与知识空间绑定",
    "department_transfer_permission_cleanup_event": "调岗权限清理事件",
    "department_transfer_permission_cleanup_item": "调岗权限清理明细",
    "developer_token": "开放接口开发者令牌",
    "evaluation": "应用评测任务",
    "failed_tuple": "OpenFGA 写入失败元组",
    "filelib_department_mapping": "文件库部门映射",
    "filelib_scheduled_sync_run_log": "文件库定时同步运行日志",
    "finetune": "模型微调任务",
    "flow": "应用/工作流",
    "flowversion": "应用版本",
    "group": "用户组",
    "groupresource": "用户组资源授权",
    "inbox_message": "站内信",
    "inbox_message_read": "站内信已读",
    "invitecode": "邀请码",
    "knowledge": "知识库/知识空间",
    "knowledge_document": "知识文档逻辑实体",
    "knowledge_document_version": "知识文档版本",
    "knowledge_file_pdf_artifact": "知识文件 PDF 产物",
    "knowledge_file_similarity_candidate": "知识文件相似候选",
    "knowledge_fulltext_outbox": "知识全文索引发件箱",
    "knowledge_migration_attempt": "知识迁移尝试记录",
    "knowledge_migration_batch": "知识迁移批次",
    "knowledge_migration_file": "知识迁移文件明细",
    "knowledge_migration_unit": "知识迁移单元",
    "knowledge_recycle_item": "知识回收站条目",
    "knowledge_space_scope": "知识空间可见范围",
    "knowledge_space_shared_storage_routing": "知识空间共享存储路由",
    "knowledge_space_tag_library": "知识空间标签库",
    "knowledge_tag_library_link": "知识空间与标签库关联",
    "knowledgefile": "知识文件",
    "linsight_execute_task": "灵思执行任务",
    "linsight_session_version": "灵思会话版本",
    "linsight_sop": "灵思 SOP",
    "linsight_sop_record": "灵思 SOP 执行记录",
    "llm_call_log": "大模型调用日志",
    "llm_model": "大模型",
    "llm_server": "大模型服务",
    "llm_token_log": "大模型 Token 用量日志",
    "markappuser": "标注任务用户",
    "markrecord": "标注记录",
    "marktask": "标注任务",
    "message_citation": "消息引用",
    "message_citation_relation": "消息与引用关系",
    "message_push_outbox": "消息推送发件箱",
    "message_session": "会话",
    "modeldeploy": "模型部署",
    "org_sync_config": "组织同步配置",
    "org_sync_log": "组织同步日志",
    "point_copy": "积分文案",
    "point_favorite_tier_award": "积分收藏档位奖励",
    "point_pending_deduct": "积分待扣减",
    "point_rank_snapshot": "积分排行快照",
    "point_rule": "积分规则",
    "point_sync_outbox": "积分同步发件箱",
    "portal_course": "门户课程",
    "portal_course_catalog": "门户课程目录",
    "portal_course_media_cleanup": "门户课程媒体清理任务",
    "portal_course_video": "门户课程视频条目",
    "portal_course_video_progress": "门户课程视频学习进度",
    "portal_hot_search_batch_run": "门户热搜批次运行",
    "portal_hot_search_candidate": "门户热搜候选",
    "portal_hot_search_snapshot": "门户热搜快照",
    "portal_recommendation_file_projection": "门户推荐文件投影",
    "presettrain": "预置训练数据",
    "qa_anonymous_alias": "专家问答匿名别名",
    "qa_answer": "专家问答回答",
    "qa_answer_adopt": "专家问答采纳记录",
    "qa_answer_eligibility": "专家问答回答资格",
    "qa_answer_vote": "专家问答回答点赞",
    "qa_comment": "专家问答评论",
    "qa_comment_vote": "专家问答评论点赞",
    "qa_expert": "专家问答专家档案",
    "qa_notification": "专家问答通知",
    "qa_publish_approver": "专家问答转公开审批人",
    "qa_publish_request": "专家问答转公开申请",
    "qa_question": "专家问答问题",
    "qa_question_invite": "专家问答邀请",
    "qa_question_vote": "专家问答问题点赞",
    "qaknowledge": "QA 知识条目",
    "recallchunk": "召回切片",
    "review_tag": "审核标签",
    "review_tag_link": "审核标签关联",
    "role": "角色",
    "roleaccess": "角色资源权限",
    "sensitive_word_policy": "敏感词策略",
    "server": "微调服务节点",
    "sftmodel": "微调模型",
    "share_link": "分享链接",
    "space_channel_member": "空间/频道成员",
    "system_dictionary": "系统字典",
    "t_gpts_tools": "工具",
    "t_gpts_tools_type": "工具分类",
    "t_report": "报告模板",
    "t_variable_value": "工作流变量值",
    "tag": "标签",
    "tag_blacklist": "标签黑名单",
    "taglink": "标签关联",
    "template": "应用模板",
    "tenant": "租户",
    "tenant_system_model_config": "租户系统模型配置",
    "tenant_workstation_config": "租户工作台配置",
    "user": "用户",
    "user_department": "用户部门关系",
    "user_link": "用户收藏/关联",
    "user_menu_access": "用户菜单授权",
    "user_point_account": "用户积分账户",
    "user_point_log": "用户积分流水",
    "user_tenant": "用户租户关系",
    "usergroup": "用户与用户组关系",
    "userrole": "用户角色关系",
}

COMMON_COLUMNS: dict[str, str] = {
    "id": "主键ID",
    "user_id": "用户ID",
    "tenant_id": "租户ID",
    "create_time": "创建时间",
    "update_time": "更新时间",
    "created_at": "创建时间",
    "updated_at": "更新时间",
    "created_time": "创建时间",
    "create_user": "创建人用户ID",
    "update_user": "最后更新人用户ID",
    "created_by": "创建人用户ID",
    "updated_by": "更新人用户ID",
    "create_id": "创建人用户ID",
    "create_user_id": "创建人用户ID",
    "operator_id": "操作人用户ID",
    "operator_name": "操作人姓名",
    "operator_user_id": "操作人用户ID",
    "operator_user_name": "操作人姓名",
    "is_delete": "是否删除：0否 1是",
    "is_deleted": "是否删除：0否 1是",
    "logic_delete": "逻辑删除：0否 1是",
    "deleted": "是否删除：0否 1是",
    "delete": "是否删除：0否 1是",
    "del_yn": "是否删除：0否 1是",
    "enabled": "是否启用：0否 1是",
    "is_enabled": "是否启用：0否 1是",
    "is_active": "是否有效：0否 1是",
    "is_shared": "是否共享给子租户：0否 1是",
    "remark": "备注",
    "description": "描述",
    "desc": "描述",
    "name": "名称",
    "title": "标题",
    "content": "内容",
    "status": "状态",
    "type": "类型",
    "source": "来源",
    "sort_order": "排序，越小越靠前",
    "sort_weight": "排序权重，越小越靠前",
    "order_index": "排序序号，越小越靠前",
    "order_num": "排序序号",
    "retry_count": "重试次数",
    "max_retries": "最大重试次数",
    "next_retry_at": "下次重试时间",
    "last_error": "最近一次错误信息",
    "error_message": "错误信息",
    "error_summary": "错误摘要",
    "error_msg": "错误信息",
    "error_details": "错误详情",
    "department_id": "部门ID",
    "dept_id": "部门ID",
    "parent_id": "父级ID",
    "knowledge_id": "知识库/知识空间ID",
    "file_id": "文件ID",
    "flow_id": "应用/工作流ID",
    "flow_type": "应用类型",
    "flow_name": "应用名称",
    "question_id": "问题ID",
    "answer_id": "回答ID",
    "message_id": "消息ID",
    "chat_id": "会话ID",
    "session_id": "会话ID",
    "space_id": "知识空间ID",
    "instance_id": "审批实例ID",
    "batch_id": "批次ID",
    "object_name": "对象存储对象名",
    "file_name": "文件名",
    "logo": "图标/封面地址",
    "user_name": "用户名",
    "external_id": "外部系统ID",
    "resource_type": "资源类型",
    "resource_id": "资源ID",
    "group_id": "用户组ID",
    "role_id": "角色ID",
    "tag_id": "标签ID",
    "version": "版本号",
    "version_no": "版本号",
    "payload_snapshot": "载荷快照JSON",
    "payload_json": "载荷JSON",
    "payload": "载荷JSON",
    "extra": "扩展信息",
    "extra_config": "扩展配置JSON",
    "extra_meta": "扩展元数据",
    "meta_data": "元数据JSON",
    "metadata": "元数据JSON",
    "config": "配置JSON",
    "data": "数据JSON",
    "artifact": "产物",
    "origin": "来源",
    "selection": "选择",
    "spaces": "空间",
    "execute": "执行",
    "feedback": "反馈",
    "description": "描述",
    "logo": "图标",
    "dept": "部门",
    "expert": "专家",
    "request": "申请",
    "answer": "回答",
    "questions": "问题列表",
    "answers": "答案列表",
    "admin": "管理员",
    "similarity": "相似度",
    "mounted": "挂载",
    "concurrent": "并发",
    "exec": "执行",
    "ment": "",
    "value": "配置值",
    "key": "配置键",
    "reason": "原因",
    "reason_code": "原因码",
    "comment": "备注/审批意见",
    "detail": "详情",
    "action": "动作",
    "event_type": "事件类型",
    "business_type": "业务类型",
    "model_name": "模型名称",
    "model_id": "模型ID",
    "server_id": "模型服务ID",
    "guide_word": "开场引导语",
    "is_primary": "是否主记录：0否 1是",
    "is_pinned": "是否置顶：0否 1是",
    "is_released": "是否已发布：0否 1是",
    "is_favorite": "是否收藏：0否 1是",
    "is_preset": "是否预置：0否 1是",
    "grant_source": "授权来源",
    "display_name": "展示名称",
    "visibility": "可见范围",
    "source_type": "来源类型",
    "level": "层级",
    "path": "路径",
    "url": "URL",
    "started_at": "开始时间",
    "finished_at": "结束时间",
    "completed_at": "完成时间",
    "start_time": "开始时间",
    "end_time": "结束时间",
    "sent_at": "发送时间",
    "expire_at": "过期时间",
    "expire_time": "过期时间",
    "decided_at": "决策时间",
    "resolved_at": "解决时间",
    "revoked_at": "撤销时间",
    "deleted_at": "删除时间",
    "computed_at": "计算时间",
    "last_earned_at": "最近获得积分时间",
    "attempt_count": "尝试次数",
    "duration_ms": "耗时毫秒",
    "duration_seconds": "时长秒",
    "vote_count": "点赞数",
    "file_type": "文件类型",
    "file_size": "文件大小字节",
    "md5": "MD5",
    "auth_type": "鉴权类型",
    "trigger_type": "触发类型",
    "action_code": "动作编码",
    "relation": "关系",
    "quota_config": "配额配置JSON",
    "prompt": "提示词",
    "group_ids": "用户组ID列表",
    "third_id": "第三方资源ID",
    "endpoint": "服务地址",
    "sft_endpoint": "微调服务地址",
    "server": "服务标识",
    "app_id": "应用ID",
    "task_id": "任务ID",
    "copied": "复制次数",
    "sensitive_status": "敏感词状态",
    "sender": "发送方",
    "receiver": "接收方",
    "files": "附件JSON",
    "attachments": "附件JSON",
    "expert_id": "专家ID",
    "expert_name": "专家姓名",
    "anonymous": "是否匿名：0否 1是",
    "reviewer_id": "审核人用户ID",
    "review_time": "审核时间",
    "request_id": "请求ID",
    "citation_id": "引用ID",
    "approval_instance_id": "审批实例ID",
    "document_id": "文档ID",
    "knowledge_file_id": "知识文件ID",
    "source_file_id": "源文件ID",
    "lease_until": "租约到期时间",
    "lease_owner": "租约持有者",
    "balance": "积分余额",
    "rule_code": "积分规则编码",
    "biz_type": "业务类型",
    "biz_id": "业务对象ID",
    "idempotency_key": "幂等键",
    "scope_id": "范围ID",
    "dashboard_id": "看板ID",
    "dataset_code": "数据集编码",
    "rank_no": "排名",
    "heat_score": "热度分",
    "intent_key": "意图键",
    "display_query": "展示查询词",
    "canonical_query": "归一查询词",
    "unique_users": "去重用户数",
    "search_count_7d": "近7日搜索次数",
    "search_count_8_30d": "8至30日搜索次数",
    "course_id": "课程ID",
    "video_id": "视频ID",
    "catalog_id": "目录ID",
    "cover_url": "封面地址",
    "instructor": "讲师",
    "organization": "所属机构",
    "tags_json": "标签JSON数组",
    "show_on_home": "是否首页展示：0否 1是",
    "course_type": "课程类型：local本地/external第三方",
    "external_url": "第三方跳转地址",
    "source_updated_at": "源系统更新时间",
    "source_url": "外链地址",
    "original_filename": "原始文件名",
    "progress_seconds": "已学秒数",
    "completed": "是否完成：0否 1是",
    "not_before": "最早可执行时间",
    "routing_path": "路由路径",
    "catalog_id_path": "目录ID物化路径",
    "catalog_name_path": "目录名称物化路径",
    "opened": "是否对门户开放：0否 1是",
    "password": "密码哈希",
    "email": "邮箱",
    "phone_number": "手机号",
    "avatar": "头像地址",
    "guid": "全局用户标识",
    "wechat_user_id": "企业微信用户ID",
    "token_version": "令牌版本",
    "password_update_time": "密码更新时间",
    "external_code": "外部工号",
    "disable_source": "停用来源",
    "tenant_code": "租户编码",
    "tenant_name": "租户名称",
    "root_dept_id": "根部门ID",
    "parent_tenant_id": "父租户ID",
    "contact_name": "联系人",
    "contact_phone": "联系电话",
    "contact_email": "联系邮箱",
    "storage_config": "存储配置JSON",
    "share_default_to_children": "是否默认共享给子租户：0否 1是",
    "is_default": "是否默认：0否 1是",
    "last_access_time": "最近访问时间",
    "join_time": "加入时间",
    "is_group_admin": "是否用户组管理员：0否 1是",
    "is_tenant_root": "是否租户根部门：0否 1是",
    "short_name": "简称",
    "role_name": "角色名称",
    "group_name": "用户组名称",
    "menu_key": "菜单键",
    "menu_name": "菜单名称",
    "share_token": "分享令牌",
    "share_mode": "分享模式",
    "access_count": "访问次数",
    "ip_address": "IP地址",
    "ip_whitelist": "IP白名单",
    "token_hash": "令牌哈希",
    "token_prefix": "令牌前缀",
    "token_ciphertext": "令牌密文",
    "rate_limit_per_minute": "每分钟限流",
    "last_used_time": "最近使用时间",
    "last_used_ip": "最近使用IP",
    "dict_key": "字典键",
    "dict_value": "字典值",
    "cron_expression": "Cron表达式",
    "provider": "提供方",
    "abstract": "摘要",
    "thumbnails": "缩略图",
    "alias_name": "别名",
    "tags": "标签列表",
    "ai_tags": "AI生成标签",
    "collection_name": "向量集合名",
    "index_name": "检索索引名",
    "system_prompt": "系统提示词",
    "temperature": "采样温度",
    "max_token": "最大Token数",
    "online": "是否上线：0否 1是",
    "latency_ms": "延迟毫秒",
    "prompt_tokens": "输入Token数",
    "completion_tokens": "输出Token数",
    "total_tokens": "总Token数",
    "like": "点赞数",
    "dislike": "点踩数",
    "liked": "是否点赞",
    "solved": "是否已解决",
    "is_bot": "是否机器人消息：0否 1是",
    "view_count": "浏览次数",
    "answer_count": "回答数",
    "comment_count": "评论数",
    "adopt_count": "采纳数",
    "adoption_count": "被采纳次数",
    "read": "是否已读：0否 1是",
    "score": "评分",
    "rating": "评分",
    "history": "历史JSON",
    "question": "问题",
    "tools": "工具配置JSON",
    "sop": "SOP内容",
    "body": "消息体",
    "chunk": "文本切片",
    "keywords": "关键词",
    "simhash": "SimHash",
    "similarity": "相似度",
    "page_count": "页数",
    "artifact_size": "产物大小字节",
    "artifact_sha256": "产物SHA256",
    "source_md5": "源文件MD5",
    "parse_type": "解析类型",
    "parse_priority": "解析优先级",
    "split_rule": "切分规则JSON",
    "allow_download": "是否允许下载：0否 1是",
    "auto_tag_enabled": "是否启用自动标签：0否 1是",
    "auto_reply": "命中提示话术",
    "custom_words": "自定义词表",
    "words_types": "词表类型",
    "scope_type": "作用域类型",
    "is_builtin": "是否内置：0否 1是",
    "is_visible": "是否可见：0否 1是",
    "is_commercial_only": "是否仅商业版：0否 1是",
    "write_frozen": "是否冻结写入：0否 1是",
    "preserve_structure": "是否保留目录结构：0否 1是",
    "preserve_link": "是否保留链接：0否 1是",
    "qualified": "是否入选：0否 1是",
    "recommendable": "是否可推荐：0否 1是",
    "truncated": "是否截断：0否 1是",
    "llm_degraded": "LLM是否降级：0否 1是",
    "snapshot_complete": "快照是否完整：0否 1是",
    "content_locked": "内容是否锁定：0否 1是",
    "asker_anonymous": "提问者是否匿名：0否 1是",
    "reveal_on_public": "转公开后是否揭示姓名：0否 1是",
    "asker_reveal_on_public": "转公开后是否公开提问者姓名：0否 1是",
    "is_follow_up": "是否追问：0否 1是",
    "adopted": "是否已采纳：0否 1是",
    "is_current": "是否当前版本：0否 1是",
    "is_list_entry": "是否列表条目：0否 1是",
    "is_option": "是否选项：0否 1是",
    "limit_flag": "是否限额：0否 1是",
    "personal_knowledge_enabled": "是否启用个人知识：0否 1是",
    "org_knowledge_enabled": "是否启用组织知识：0否 1是",
    "has_reexecute": "是否已重执行：0否 1是",
    "showcase": "是否展示：0否 1是",
    "portal_discovery_enabled": "是否门户可发现：0否 1是",
    "shared_enabled": "是否启用共享：0否 1是",
    "approval_enabled": "是否启用审批：0否 1是",
    "sensitive_check_enabled": "是否启用敏感词检查：0否 1是",
    "override_ip_whitelist": "是否覆盖IP白名单：0否 1是",
    "override_rate_limit": "是否覆盖限流：0否 1是",
    "is_shared_to_children": "是否共享给子租户：0否 1是",
    "grant_include_children": "是否包含子部门：0否 1是",
    "data_config": "数据配置JSON",
    "mounted_tenant_id": "挂载的子租户ID",
    "concurrent_session_limit": "并发会话上限",
    "exec_type": "执行类型",
    "train_data": "训练数据",
    "preset_data": "预置训练数据",
    "artifact_origin": "产物来源",
    "refined_similarity": "精炼相似度",
    "source_selection_snapshot": "源选择快照",
    "source_spaces_snapshot": "源空间快照",
    "task_data": "任务数据JSON",
    "execute_feedback": "执行反馈",
    "flow_description": "应用描述",
    "flow_logo": "应用图标",
    "dept_created": "新建部门数",
    "dept_updated": "更新部门数",
    "dept_archived": "归档部门数",
    "member_created": "新建成员数",
    "member_updated": "更新成员数",
    "member_disabled": "停用成员数",
    "member_reactivated": "恢复成员数",
    "expert_user_id": "专家用户ID",
    "depart_ment": "所属部门JSON",
    "job_family": "职位族",
    "job_category": "职位类",
    "role_in_request": "在该申请中的角色",
    "active_publish_request_id": "当前有效转公开申请ID",
    "adopted_answer_id": "已采纳回答ID",
    "questions": "问题列表",
    "answers": "答案列表",
    "department_admin_promoted_from_role": "提升为部门管理员前的角色",
    "bbox_object_name": "坐标框对象名",
    "preview_file_object_name": "预览文件对象名",
}

TABLE_COLUMN_COMMENTS: dict[tuple[str, str], str] = {
    ("config", "key"): "配置键",
    ("config", "value"): "配置值",
    ("config", "comment"): "配置说明",
    ("user", "user_id"): "用户ID（主键）",
    ("user", "user_name"): "登录名",
    ("user", "source"): "账号来源：local/feishu/wecom/dingtalk等",
    ("tenant_system_model_config", "key"): "配置键：linsight_llm/knowledge_llm等",
    ("tenant_system_model_config", "value"): "配置JSON",
    ("tenant_workstation_config", "key"): "配置键",
    ("tenant_workstation_config", "value"): "配置值JSON",
    ("flow", "status"): "状态：1下线 2上线",
    ("flow", "data"): "工作流图JSON",
    ("assistant", "status"): "助手状态",
    ("knowledge", "type"): "知识库类型",
    ("knowledge", "state"): "知识库状态",
    ("knowledgefile", "status"): "文件处理状态",
    ("approval_request", "status"): "申请单状态",
    ("approval_request", "request_type"): "申请类型",
    ("approval_instance", "status"): "审批实例状态",
    ("approval_task", "status"): "任务状态",
    ("approval_task", "comment"): "审批意见",
    ("developer_token", "status"): "令牌状态",
    ("developer_token", "enabled"): "是否启用：0否 1是",
    ("point_rule", "status"): "规则状态",
    ("point_pending_deduct", "status"): "待扣减状态",
    ("point_sync_outbox", "status"): "同步状态",
    ("portal_course_media_cleanup", "status"): "任务状态：pending/leased/done/failed",
    ("portal_course_media_cleanup", "reason"): "清理原因：provisional/replaced/deleted等",
    ("portal_course", "name"): "课程名称",
    ("portal_course", "description"): "课程介绍",
    ("portal_course", "enabled"): "是否上架：0否 1是",
    ("portal_course_catalog", "name"): "目录名称",
    ("portal_course_catalog", "description"): "目录简介",
    ("portal_course_video", "title"): "视频标题",
    ("portal_course_video", "source_type"): "来源类型：upload上传/url外链",
    ("qa_expert", "status"): "专家状态：1有效 0停用",
    ("qa_question", "status"): "问题状态",
    ("qa_question", "question_type"): "问题类型：directed定向/public公开",
    ("qa_answer", "status"): "回答状态",
    ("qa_publish_request", "status"): "转公开申请状态",
    ("sensitive_word_policy", "enabled"): "是否启用：0否 1是",
    ("share_link", "status"): "分享状态",
    ("message_push_outbox", "status"): "推送状态",
    ("inbox_message", "status"): "站内信状态",
    ("org_sync_config", "status"): "配置状态：active/disabled/deleted",
    ("org_sync_log", "status"): "同步结果状态",
    ("dashboard", "status"): "看板状态",
    ("role", "role_type"): "角色类型",
    ("chatmessage", "type"): "消息类型",
    ("chatmessage", "category"): "消息分类",
    ("t_variable_value", "value"): "变量值",
    ("t_gpts_tools", "type"): "工具类型",
    ("llm_model", "model_type"): "模型类型",
    ("llm_server", "type"): "服务类型",
    ("knowledge_fulltext_outbox", "status"): "发件箱状态",
    ("knowledge_migration_batch", "status"): "迁移批次状态",
    ("knowledge_recycle_item", "status"): "回收站条目状态",
    ("linsight_execute_task", "status"): "任务状态",
    ("linsight_session_version", "status"): "会话版本状态",
    ("evaluation", "status"): "评测状态",
    ("finetune", "status"): "微调任务状态",
    ("marktask", "status"): "标注任务状态",
    ("failed_tuple", "status"): "重试状态：pending/succeeded/dead",
    ("failed_tuple", "action"): "动作：write/delete",
    ("failed_tuple", "object"): "OpenFGA object",
    ("failed_tuple", "fga_user"): "OpenFGA user",
    ("failed_tuple", "relation"): "OpenFGA relation",
    ("space_channel_member", "status"): "成员状态",
    ("department_file_view_grant", "status"): "授权状态",
    ("department_transfer_permission_cleanup_event", "status"): "清理事件状态",
    ("user_menu_access", "status"): "授权状态",
    ("user_tenant", "status"): "关系状态：active/disabled",
    ("department", "status"): "部门状态",
    ("tenant", "status"): "租户状态：active/disabled/archived/orphaned",
}

TOKEN_MAP: dict[str, str] = {
    "id": "ID",
    "ids": "ID列表",
    "tenant": "租户",
    "user": "用户",
    "name": "名称",
    "code": "编码",
    "key": "键",
    "type": "类型",
    "status": "状态",
    "source": "来源",
    "target": "目标",
    "create": "创建",
    "update": "更新",
    "delete": "删除",
    "deleted": "已删除",
    "time": "时间",
    "at": "时间",
    "count": "数量",
    "num": "序号",
    "no": "编号",
    "json": "JSON",
    "snapshot": "快照",
    "config": "配置",
    "path": "路径",
    "url": "地址",
    "file": "文件",
    "folder": "文件夹",
    "space": "空间",
    "knowledge": "知识",
    "document": "文档",
    "version": "版本",
    "model": "模型",
    "server": "服务",
    "token": "令牌",
    "hash": "哈希",
    "error": "错误",
    "retry": "重试",
    "lease": "租约",
    "grant": "授权",
    "revoke": "撤销",
    "revoked": "已撤销",
    "protect": "保护",
    "protected": "已保护",
    "reason": "原因",
    "summary": "摘要",
    "detail": "详情",
    "message": "消息",
    "operator": "操作人",
    "applicant": "申请人",
    "approver": "审批人",
    "reviewer": "审核人",
    "receiver": "接收人",
    "sender": "发送人",
    "department": "部门",
    "role": "角色",
    "menu": "菜单",
    "node": "节点",
    "flow": "流程",
    "task": "任务",
    "batch": "批次",
    "unit": "单元",
    "item": "条目",
    "event": "事件",
    "action": "动作",
    "payload": "载荷",
    "schema": "结构",
    "index": "索引",
    "object": "对象",
    "original": "原始",
    "current": "当前",
    "previous": "上一",
    "next": "下一",
    "parent": "父",
    "child": "子",
    "root": "根",
    "level": "层级",
    "order": "排序",
    "sort": "排序",
    "weight": "权重",
    "score": "分数",
    "rank": "排名",
    "start": "开始",
    "end": "结束",
    "begin": "开始",
    "finish": "结束",
    "complete": "完成",
    "completed": "已完成",
    "success": "成功",
    "failed": "失败",
    "skip": "跳过",
    "skipped": "已跳过",
    "fail": "失败",
    "total": "总计",
    "unique": "去重",
    "distinct": "去重",
    "window": "窗口",
    "period": "周期",
    "scope": "范围",
    "limit": "上限",
    "flag": "标记",
    "enabled": "启用",
    "disabled": "停用",
    "shared": "共享",
    "default": "默认",
    "primary": "主",
    "extra": "扩展",
    "meta": "元数据",
    "tag": "标签",
    "tags": "标签",
    "ai": "AI",
    "llm": "大模型",
    "embedding": "向量",
    "vector": "向量",
    "store": "存储",
    "routing": "路由",
    "migration": "迁移",
    "recycle": "回收站",
    "preview": "预览",
    "bbox": "坐标框",
    "page": "页",
    "size": "大小",
    "sha": "哈希",
    "md": "MD",
    "generation": "代数",
    "revision": "修订号",
    "checkpoint": "检查点",
    "attempt": "尝试",
    "round": "轮次",
    "worker": "工作线程",
    "execution": "执行",
    "preflight": "预检",
    "conflict": "冲突",
    "strategy": "策略",
    "overwrite": "覆盖",
    "preserve": "保留",
    "structure": "结构",
    "link": "链接",
    "manifest": "清单",
    "mapping": "映射",
    "planned": "计划",
    "applied": "已应用",
    "desired": "期望",
    "projection": "投影",
    "permission": "权限",
    "relation": "关系",
    "subject": "主体",
    "binding": "绑定",
    "membership": "成员关系",
    "promoted": "提升",
    "include": "包含",
    "children": "子级",
    "fingerprint": "指纹",
    "owner": "拥有者",
    "builtin": "内置",
    "library": "库",
    "blacklist": "黑名单",
    "whitelist": "白名单",
    "route": "路由",
    "rate": "速率",
    "minute": "分钟",
    "cipher": "密文",
    "prefix": "前缀",
    "sync": "同步",
    "scope": "范围",
    "cron": "Cron",
    "schedule": "调度",
    "provider": "提供方",
    "auth": "鉴权",
    "host": "主机",
    "openapi": "OpenAPI",
    "api": "API",
    "params": "参数",
    "method": "方法",
    "endpoint": "地址",
    "latency": "延迟",
    "ms": "毫秒",
    "seconds": "秒",
    "duration": "时长",
    "progress": "进度",
    "video": "视频",
    "course": "课程",
    "catalog": "目录",
    "cover": "封面",
    "instructor": "讲师",
    "organization": "机构",
    "home": "首页",
    "opened": "开放",
    "query": "查询",
    "intent": "意图",
    "canonical": "归一",
    "heat": "热度",
    "rewrite": "改写",
    "sample": "样本",
    "candidate": "候选",
    "dedup": "去重",
    "qualified": "入选",
    "truncated": "截断",
    "degraded": "降级",
    "scanned": "扫描",
    "es": "ES",
    "pages": "页数",
    "member": "成员",
    "calls": "调用次数",
    "group": "组",
    "final": "最终",
    "display": "展示",
    "business": "业务",
    "domain": "域",
    "codes": "编码列表",
    "fields": "字段",
    "state": "状态",
    "favorite": "收藏",
    "released": "已发布",
    "pinned": "置顶",
    "shared": "共享",
    "online": "在线",
    "preset": "预置",
    "train": "训练",
    "report": "报告",
    "log": "日志",
    "base": "基座",
    "root": "根",
    "rt": "推理",
    "sft": "微调",
    "deploy": "部署",
    "tool": "工具",
    "tools": "工具",
    "assistant": "助手",
    "system": "系统",
    "guide": "引导",
    "word": "文案",
    "question": "问题",
    "temperature": "温度",
    "max": "最大",
    "min": "最小",
    "token": "Token",
    "copied": "复制",
    "liked": "点赞",
    "solved": "已解决",
    "sensitive": "敏感",
    "intermediate": "中间",
    "steps": "步骤",
    "receiver": "接收方",
    "sender": "发送方",
    "category": "分类",
    "mark": "标注",
    "process": "处理",
    "users": "用户",
    "invite": "邀请",
    "used": "已使用",
    "bind": "绑定",
    "batch": "批次",
    "limit": "上限",
    "note": "说明",
    "ip": "IP",
    "address": "地址",
    "target": "目标",
    "object": "对象",
    "system": "系统",
    "event": "事件",
    "audit": "审计",
    "template": "模板",
    "variable": "变量",
    "option": "选项",
    "node": "节点",
    "chunk": "切片",
    "keywords": "关键词",
    "recall": "召回",
    "citation": "引用",
    "inbox": "站内信",
    "push": "推送",
    "body": "正文",
    "failure": "失败",
    "wechat": "企微",
    "recipient": "接收人",
    "notification": "通知",
    "vote": "点赞",
    "adopt": "采纳",
    "adopted": "已采纳",
    "alias": "别名",
    "ord": "序号",
    "label": "标签",
    "eligibility": "资格",
    "publish": "公开",
    "approver": "审批人",
    "decision": "决定",
    "initiator": "发起人",
    "extension": "延期",
    "days": "天数",
    "expire": "过期",
    "follow": "追",
    "up": "问",
    "images": "图片",
    "image": "图片",
    "related": "相关",
    "docs": "文档",
    "invited": "已邀请",
    "experts": "专家",
    "names": "名称",
    "introduction": "简介",
    "major": "专业",
    "position": "岗位",
    "job": "职位",
    "family": "族",
    "depart": "部门",
    "ment": "",
    "locked": "锁定",
    "asker": "提问者",
    "reveal": "揭示",
    "public": "公开",
    "active": "当前",
    "view": "浏览",
    "comment": "评论",
    "safety": "安全",
    "decision": "结论",
    "finalized": "办结",
    "decided": "已决策",
    "review": "审核",
    "mode": "模式",
    "parent": "父",
    "folder": "目录",
    "reject": "驳回",
    "invalidated": "已失效",
    "granted": "已授权",
    "scenario": "场景",
    "handler": "处理器",
    "route": "路由",
    "match": "匹配",
    "definition": "定义",
    "exception": "异常",
    "resolved": "已处理",
    "acted": "已操作",
    "current": "当前",
    "latest": "最近",
    "article": "文章",
    "channel": "频道",
    "sub": "子",
    "filter": "过滤",
    "rules": "规则",
    "icon": "图标",
    "list": "列表",
    "layout": "布局",
    "style": "样式",
    "dataset": "数据集",
    "dashboard": "看板",
    "visible": "可见",
    "commercial": "商业版",
    "only": "仅",
    "group": "分组",
    "title": "标题",
    "copy": "文案",
    "period": "周期",
    "refreshed": "刷新",
    "highest": "最高",
    "tier": "档位",
    "points": "积分",
    "granted": "已发放",
    "lifetime": "累计",
    "earned": "获得",
    "deducted": "扣减",
    "delta": "变动值",
    "after": "之后",
    "direction": "方向",
    "beneficiary": "受益角色",
    "occurred": "发生",
    "expr": "表达式",
    "cap": "上限",
    "daily": "每日",
    "pending": "待处理",
    "outbox": "发件箱",
    "log": "流水",
    "account": "账户",
    "old": "原",
    "new": "新",
    "deadline": "截止",
    "overdue": "逾期",
    "requested": "申请",
    "changed": "变更",
    "processed": "已处理",
    "protected": "受保护",
    "revoked": "已回收",
    "skipped": "已跳过",
    "complete": "完整",
    "ref": "引用",
    "cleanup": "清理",
    "transfer": "调动",
    "trigger": "触发",
    "external": "外部",
    "org": "组织",
    "member": "成员",
    "archived": "已归档",
    "reactivated": "已恢复",
    "created": "新建",
    "updated": "更新",
    "disabled": "停用",
    "ts": "时间戳",
    "job": "任务",
    "developer": "开发者",
    "duration": "耗时",
    "mapping": "映射",
    "failure": "失败",
    "inbox": "站内信",
    "wechat": "企微",
    "openid": "OpenID",
    "host": "主机",
    "openapi": "OpenAPI",
    "params": "参数",
    "preset": "预置",
    "call": "调用",
    "msg": "信息",
    "personal": "个人",
    "org": "组织",
    "output": "输出",
    "result": "结果",
    "reexecute": "重执行",
    "showcase": "展示",
    "session": "会话",
    "sop": "SOP",
    "feedback": "反馈",
    "linsight": "灵思",
    "vector": "向量",
    "store": "库",
    "online": "上线",
    "shared": "共享",
    "children": "子租户",
    "discovery": "发现",
    "portal": "门户",
    "frozen": "冻结",
    "write": "写入",
    "routing": "路由",
    "schema": "结构",
    "fingerprint": "指纹",
    "owner": "拥有者",
    "library": "标签库",
    "builtin": "内置",
    "ai": "AI",
    "window": "窗口",
    "distinct": "去重",
    "candidate": "候选",
    "dedup": "去重",
    "record": "记录",
    "qualified": "入选",
    "rewrite": "改写",
    "sample": "样本",
    "member": "成员",
    "queries": "查询词",
    "final": "最终",
    "recommendable": "可推荐",
    "permission": "权限",
    "projection": "投影",
    "updater": "更新人",
    "uploader": "上传人",
    "original": "原始",
    "reference": "引用",
    "entry": "条目",
    "share": "分享",
    "download": "下载",
    "allow": "允许",
    "desired": "期望",
    "applied": "已应用",
    "content": "内容",
    "generation": "代数",
    "lifecycle": "生命周期",
    "predecessor": "前驱",
    "logic": "逻辑",
    "primary": "主",
    "preview": "预览",
    "bbox": "坐标",
    "parse": "解析",
    "priority": "优先级",
    "split": "切分",
    "rule": "规则",
    "encoding": "编码",
    "subcategory": "小类",
    "similar": "相似",
    "refined": "精炼",
    "candidate": "候选",
    "aggregate": "聚合",
    "fanout": "扇出",
    "cursor": "游标",
    "revision": "修订",
    "lease": "租约",
    "until": "截止",
    "owner": "持有者",
    "success": "成功",
    "last": "最近",
    "first": "首次",
    "scanned": "已扫描",
    "executable": "可执行",
    "succeeded": "成功",
    "unprocessed": "未处理",
    "overwrite": "覆盖",
    "preflight": "预检",
    "execution": "执行",
    "confirmed": "已确认",
    "abandoned": "已放弃",
    "queued": "已入队",
    "stage": "阶段",
    "round": "轮次",
    "worker": "工作",
    "checkpoint": "检查点",
    "attempt": "尝试",
    "unit": "单元",
    "planned": "计划",
    "mapping": "映射",
    "manifest": "清单",
    "resource": "资源",
    "metadata": "元数据",
    "recycle": "回收",
    "fingerprint": "指纹",
    "label": "标签",
    "category": "类目",
    "tags": "标签",
    "root": "根",
    "list": "列表",
    "entry": "条目",
    "by": "操作人",
    "from": "来源",
    "to": "目标",
    "of": "",
    "the": "",
    "a": "",
    "an": "",
    "and": "",
    "or": "",
    "on": "",
    "in": "",
    "for": "",
    "with": "",
}


def _is_cjk(text: str) -> bool:
    return any("\u4e00" <= ch <= "\u9fff" for ch in text)


def _heuristic_comment(column: str) -> str:
    if column in COMMON_COLUMNS:
        return COMMON_COLUMNS[column]
    parts = [p for p in column.split("_") if p]
    mapped: list[str] = []
    for part in parts:
        token = TOKEN_MAP.get(part)
        if token:
            mapped.append(token)
        elif part.endswith("id") and len(part) > 2:
            mapped.append(part[:-2] + "ID")
        else:
            mapped.append(part)
    text = "".join(mapped).strip()
    return text or column


def _column_comment(table: str, column: str, orm_comment: str) -> str:
    specific = TABLE_COLUMN_COMMENTS.get((table, column))
    if specific:
        return specific
    if column in COMMON_COLUMNS:
        return COMMON_COLUMNS[column]
    if orm_comment and _is_cjk(orm_comment):
        return orm_comment
    return _heuristic_comment(column)


def _table_comment(table: str, orm_comment: str) -> str:
    if table in TABLE_COMMENTS:
        return TABLE_COMMENTS[table]
    if orm_comment and _is_cjk(orm_comment):
        return orm_comment
    return table


def _sql_str(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def _import_models() -> None:
    root = Path(bisheng.__file__).parent
    for py in sorted(root.rglob("*.py")):
        rel = py.relative_to(root)
        parts = rel.with_suffix("").parts
        if any(p in {"test", "tests", "__pycache__", "alembic"} for p in parts):
            continue
        if "models" not in parts:
            continue
        try:
            importlib.import_module("bisheng." + ".".join(parts))
        except Exception:
            continue


SQL_HEADER = r"""-- 一次性 MySQL 脚本：为 COMMENT 为空的表和字段补中文备注。
-- 已有备注不会覆盖；表或字段不存在则跳过；可重复执行。
-- 字段备注通过 MODIFY COLUMN 写入，会保留原类型/空值/默认值/AUTO_INCREMENT。
-- 请用 mysql 客户端在目标库低峰执行，并先备份。不要用 execute_sql.py（不支持 DELIMITER）。
--
--   mysql -u USER -p DATABASE < src/backend/scripts/sql/fill_mysql_table_column_comments.sql

SET NAMES utf8mb4;

DROP PROCEDURE IF EXISTS tmp_fill_column_comment;
DROP PROCEDURE IF EXISTS tmp_fill_table_comment;

DELIMITER $$

CREATE PROCEDURE tmp_fill_table_comment(
  IN p_table VARCHAR(64),
  IN p_comment VARCHAR(2048)
)
BEGIN
  DECLARE v_exists INT DEFAULT 0;
  DECLARE v_cur TEXT;

  SELECT COUNT(*) INTO v_exists
    FROM information_schema.TABLES
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = p_table;

  IF v_exists > 0 THEN
    SELECT IFNULL(TABLE_COMMENT, '') INTO v_cur
      FROM information_schema.TABLES
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = p_table
     LIMIT 1;
    IF v_cur IS NULL OR TRIM(v_cur) = '' THEN
      SET @sql = CONCAT('ALTER TABLE `', p_table, '` COMMENT = ', QUOTE(p_comment));
      PREPARE stmt FROM @sql;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
    END IF;
  END IF;
END $$

CREATE PROCEDURE tmp_fill_column_comment(
  IN p_table VARCHAR(64),
  IN p_column VARCHAR(64),
  IN p_comment VARCHAR(1024)
)
BEGIN
  DECLARE v_type LONGTEXT;
  DECLARE v_nullable VARCHAR(8);
  DECLARE v_default LONGTEXT;
  DECLARE v_extra VARCHAR(512);
  DECLARE v_cur TEXT;
  DECLARE v_null_sql VARCHAR(16);
  DECLARE v_sql LONGTEXT;
  DECLARE v_extra_l VARCHAR(512);

  SELECT COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, EXTRA, COLUMN_COMMENT
    INTO v_type, v_nullable, v_default, v_extra, v_cur
    FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME = p_table
     AND COLUMN_NAME = p_column
   LIMIT 1;

  IF v_type IS NOT NULL
     AND (v_cur IS NULL OR TRIM(v_cur) = '')
     AND LOWER(IFNULL(v_extra, '')) NOT LIKE '%generated%' THEN
    SET v_null_sql = IF(v_nullable = 'YES', 'NULL', 'NOT NULL');
    SET v_sql = CONCAT('ALTER TABLE `', p_table, '` MODIFY COLUMN `', p_column, '` ', v_type, ' ', v_null_sql);
    SET v_extra_l = LOWER(IFNULL(v_extra, ''));

    IF v_default IS NOT NULL THEN
      IF UPPER(v_default) IN ('CURRENT_TIMESTAMP', 'CURRENT_TIMESTAMP()', 'NULL')
         OR UPPER(v_default) LIKE 'CURRENT_TIMESTAMP%' THEN
        SET v_sql = CONCAT(v_sql, ' DEFAULT ', v_default);
      ELSE
        SET v_sql = CONCAT(v_sql, ' DEFAULT ', QUOTE(v_default));
      END IF;
    END IF;

    IF v_extra_l LIKE '%auto_increment%' THEN
      SET v_sql = CONCAT(v_sql, ' AUTO_INCREMENT');
    END IF;
    IF v_extra_l LIKE '%on update current_timestamp%' THEN
      SET v_sql = CONCAT(v_sql, ' ON UPDATE CURRENT_TIMESTAMP');
    END IF;

    SET v_sql = CONCAT(v_sql, ' COMMENT ', QUOTE(p_comment));
    SET @sql = v_sql;
    PREPARE stmt FROM @sql;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
  END IF;
END $$

DELIMITER ;

"""

SQL_FOOTER = """
DROP PROCEDURE IF EXISTS tmp_fill_column_comment;
DROP PROCEDURE IF EXISTS tmp_fill_table_comment;
"""


def main() -> None:
    _import_models()
    meta = dict(SQLModel.metadata.tables)
    for key, table in SQLModelSerializable.metadata.tables.items():
        meta.setdefault(key, table)

    table_calls: list[str] = ["-- 表备注"]
    column_calls: list[str] = ["-- 字段备注"]
    missing_table_names: list[str] = []
    table_count = 0
    column_count = 0

    for name, table in sorted(meta.items()):
        if name.startswith("_"):
            continue
        t_comment = _table_comment(name, (table.comment or "").strip())
        if name not in TABLE_COMMENTS:
            missing_table_names.append(name)
        table_calls.append(
            f"CALL tmp_fill_table_comment({_sql_str(name)}, {_sql_str(t_comment)});"
        )
        table_count += 1
        column_calls.append(f"-- {name}")
        for col in table.columns:
            c_comment = _column_comment(name, col.name, (col.comment or "").strip())
            if len(c_comment) > 1024:
                c_comment = c_comment[:1024]
            column_calls.append(
                "CALL tmp_fill_column_comment("
                f"{_sql_str(name)}, {_sql_str(col.name)}, {_sql_str(c_comment)});"
            )
            column_count += 1

    out = Path(__file__).resolve().parent / "sql" / "fill_mysql_table_column_comments.sql"
    out.write_text(
        SQL_HEADER
        + "\n".join(table_calls)
        + "\n\n"
        + "\n".join(column_calls)
        + "\n"
        + SQL_FOOTER,
        encoding="utf-8",
    )
    print(f"wrote {out}")
    print(f"tables={table_count} columns={column_count}")
    if missing_table_names:
        print("missing TABLE_COMMENTS:", ", ".join(missing_table_names))


if __name__ == "__main__":
    main()
