#!/usr/bin/env python3
"""Publish the current OpenFGA authorization-model change.

Use this script after the code-owned authorization model changes but the F048
control-plane actions/models and resource Grants do not need a formal data
migration. It writes or reuses the immutable OpenFGA model generated by the
current code, persists the authorization-model release row, and publishes a
no-op Permission Catalog release that points CURRENT at the new model.

Run from ``src/backend`` with the live ``config`` value::

    PYTHONPATH=./ .venv/bin/python scripts/publish_authorization_model_change.py
    PYTHONPATH=./ .venv/bin/python scripts/publish_authorization_model_change.py \
      --apply \
      --confirm-store-id <store-id> \
      --confirm-target-model-checksum <target-model-checksum> \
      --operator-id <operator-user-id>

Dry-run is the default. Apply refuses active F048 runtime heartbeats, in-flight
permission projection operations, a write-fenced CURRENT Catalog, or a Store /
checksum confirmation mismatch.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import traceback
from dataclasses import asdict, dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

_BACKEND_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _BACKEND_ROOT not in sys.path:
    sys.path.insert(0, _BACKEND_ROOT)

from sqlalchemy import func, update  # noqa: E402
from sqlmodel import select  # noqa: E402

from bisheng.common.services.config_service import settings  # noqa: E402
from bisheng.core.context.manager import (  # noqa: E402
    close_app_context,
    initialize_app_context,
)
from bisheng.core.context.tenant import bypass_tenant_filter  # noqa: E402
from bisheng.core.database import get_async_db_session  # noqa: E402
from bisheng.core.openfga.authorization_model_f048 import (  # noqa: E402
    MODEL_VERSION,
    authorization_model_checksum,
    get_authorization_model_f048,
)
from bisheng.core.openfga.client import FGAClient  # noqa: E402
from bisheng.core.openfga.discovery import (  # noqa: E402
    discover_openfga_runtime,
    normalize_authorization_model,
)
from bisheng.core.openfga.runtime_heartbeat import list_runtime_heartbeats  # noqa: E402
from bisheng.permission.application.catalog_api import (  # noqa: E402
    OpenFGACatalogProjector,
    SqlCatalogImpact,
    SqlCatalogState,
)
from bisheng.permission.application.sql_runtime import RedisConsistencyMarker  # noqa: E402
from bisheng.permission.domain.models import (  # noqa: E402
    AuthorizationModelRelease,
    PermissionCatalogRelease,
    PermissionProjectionOperation,
)
from bisheng.permission.domain.services.catalog_service import (  # noqa: E402
    CatalogDraftBuildInput,
    CatalogService,
)
from bisheng.permission.domain.services.model_policy import CustomModelSelection  # noqa: E402
from bisheng.permission.migration.f048_runtime_storage import (  # noqa: E402
    OpenFGAMigrationModelPublisher,
)

EXIT_OK = 0
EXIT_BLOCKED = 3
EXIT_RUNTIME_ERROR = 4
ACTIVE_OPERATION_STATUSES = ("PREPARED", "STAGING", "COMMIT_UNKNOWN", "COMMITTED")


class AuthorizationModelPublishBlockedError(RuntimeError):
    """A runtime safety condition blocked authorization-model publication."""


@dataclass(frozen=True, slots=True)
class CurrentRelease:
    catalog_id: int
    catalog_key: str
    environment: str
    store_id: str
    model_id: str
    model_release_id: int
    model_checksum: str
    write_fenced: bool


@dataclass(frozen=True, slots=True)
class PublishReport:
    mode: str
    environment: str
    store_id: str
    current_catalog_id: int
    current_model_id: str
    current_model_checksum: str
    latest_openfga_model_id: str
    latest_openfga_model_checksum: str
    target_model_id: str | None
    target_model_checksum: str
    model_version: str
    catalog_write_fenced: bool
    needs_model_publish: bool
    needs_catalog_cutover: bool


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Publish/reuse the latest model and switch the CURRENT Catalog pin",
    )
    parser.add_argument(
        "--confirm-store-id",
        default=None,
        help="Required with --apply; must equal the discovered immutable Store ID",
    )
    parser.add_argument(
        "--confirm-target-model-checksum",
        default=None,
        help="Required with --apply; must equal the dry-run target_model_checksum",
    )
    parser.add_argument(
        "--operator-id",
        type=int,
        default=0,
        help="Audit operator ID recorded on the no-op Catalog release",
    )
    args = parser.parse_args(argv)
    if args.apply and not args.confirm_store_id:
        parser.error("--apply requires --confirm-store-id")
    if args.apply and not args.confirm_target_model_checksum:
        parser.error("--apply requires --confirm-target-model-checksum")
    return args


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise AuthorizationModelPublishBlockedError(message)


def _environment_name(value: str | dict[str, Any]) -> str:
    if isinstance(value, dict):
        value = next(
            (value[key] for key in ("name", "environment", "env", "mode") if value.get(key)),
            "dev",
        )
    return str(value or "dev")[:64]


def _offline_settings(live_settings: Any) -> Any:
    openfga = getattr(live_settings, "openfga", None)
    copy_settings = getattr(live_settings, "model_copy", None)
    copy_openfga = getattr(openfga, "model_copy", None)
    if not callable(copy_settings) or not callable(copy_openfga):
        return live_settings
    return copy_settings(update={"openfga": copy_openfga(update={"enabled": False})})


async def _load_current_release() -> CurrentRelease:
    with bypass_tenant_filter():
        async with get_async_db_session() as session:
            rows = list(
                (
                    await session.exec(
                        select(PermissionCatalogRelease, AuthorizationModelRelease)
                        .join(
                            AuthorizationModelRelease,
                            AuthorizationModelRelease.id
                            == PermissionCatalogRelease.required_authorization_model_release_id,
                        )
                        .where(PermissionCatalogRelease.status == "CURRENT")
                    )
                ).all()
            )
    _require(len(rows) == 1, "Permission Catalog must have exactly one CURRENT release")
    catalog, model = rows[0]
    _require(model.status == "ACTIVE", "CURRENT Authorization Model release is not ACTIVE")
    _require(catalog.id is not None and model.id is not None, "CURRENT release identity is incomplete")
    return CurrentRelease(
        catalog_id=int(catalog.id),
        catalog_key=catalog.release_key,
        environment=model.environment,
        store_id=model.store_id,
        model_id=model.model_id,
        model_release_id=int(model.id),
        model_checksum=model.model_checksum,
        write_fenced=bool(catalog.write_fenced),
    )


async def _assert_apply_window() -> None:
    with bypass_tenant_filter():
        async with get_async_db_session() as session:
            active_operations = int(
                (
                    await session.exec(
                        select(func.count(PermissionProjectionOperation.id)).where(
                            PermissionProjectionOperation.status.in_(ACTIVE_OPERATION_STATUSES)
                        )
                    )
                ).one()
            )
    _require(active_operations == 0, f"{active_operations} permission projection operations are active")
    heartbeats = await list_runtime_heartbeats()
    _require(not heartbeats, f"{len(heartbeats)} F048 runtime heartbeats are still active")


async def _find_remote_model_id(client: FGAClient, checksum: str) -> str | None:
    for raw_model in await client.list_authorization_models():
        normalized = normalize_authorization_model(raw_model)
        if authorization_model_checksum(normalized) == checksum:
            model_id = raw_model.get("id") or raw_model.get("authorization_model_id")
            if model_id:
                return str(model_id)
    return None


async def _authorization_release_id(environment: str, store_id: str, model_id: str) -> int:
    with bypass_tenant_filter():
        async with get_async_db_session() as session:
            row = (
                await session.exec(
                    select(AuthorizationModelRelease).where(
                        AuthorizationModelRelease.environment == environment,
                        AuthorizationModelRelease.store_id == store_id,
                        AuthorizationModelRelease.model_id == model_id,
                    )
                )
            ).first()
    _require(row is not None and row.id is not None, "target Authorization Model release is missing")
    return int(row.id)


async def _activate_model_release(release_id: int) -> None:
    with bypass_tenant_filter():
        async with get_async_db_session() as session:
            async with session.begin():
                await session.execute(
                    update(AuthorizationModelRelease)
                    .where(AuthorizationModelRelease.id == release_id)
                    .values(status="ACTIVE", activated_at=func.now(), retired_at=None)
                )


async def _retire_other_active_models(current: CurrentRelease) -> None:
    with bypass_tenant_filter():
        async with get_async_db_session() as session:
            async with session.begin():
                await session.execute(
                    update(AuthorizationModelRelease)
                    .where(
                        AuthorizationModelRelease.environment == current.environment,
                        AuthorizationModelRelease.store_id == current.store_id,
                        AuthorizationModelRelease.id != current.model_release_id,
                        AuthorizationModelRelease.status == "ACTIVE",
                    )
                    .values(status="RETIRED", retired_at=func.now())
                )


async def _publish_noop_catalog_cutover(
    *,
    current: CurrentRelease,
    target_client: FGAClient,
    target_release_id: int,
    operator_id: int,
    target_checksum: str,
) -> int:
    state = SqlCatalogState()
    before = await state.load_snapshot(current.catalog_id)
    _require(
        before.action_release is not None and before.model_release is not None,
        "CURRENT Catalog snapshot is incomplete",
    )
    idempotency_key = f"auth-model-{target_checksum[:32]}"
    reservation = await state.reserve_draft(
        base_release_id=current.catalog_id,
        operator_id=operator_id,
        idempotency_key=idempotency_key,
        expires_at=datetime.now(UTC).replace(tzinfo=None) + timedelta(minutes=30),
    )
    impact = SqlCatalogImpact()
    marker = RedisConsistencyMarker()
    await marker.initialize()
    service = CatalogService(
        state=state,
        impact=impact,
        projector=OpenFGACatalogProjector(client=target_client, marker=marker),
    )
    if not reservation.complete:
        customs = tuple(
            CustomModelSelection(
                model_key=model.model_key,
                name=model.name,
                action_codes=model.selected_action_codes,
                active=model.active,
                allow_same_level=model.allow_same_level,
                config_scope=model.config_scope,
            )
            for model in before.model_release.models
            if model.kind == "CUSTOM"
        )
        standard_policy = {
            model.model_key: model.allow_same_level for model in before.model_release.models if model.kind == "STANDARD"
        }
        await service.build_draft(
            CatalogDraftBuildInput(
                release_id=reservation.release_id,
                release_key=reservation.release_key,
                predecessor_release_id=reservation.predecessor_id,
                predecessor_release_key=reservation.predecessor_key,
                before_actions=before.action_release,
                before_models=before.model_release,
                actions=before.action_release.actions,
                custom_models=customs,
                standard_allow_same_level=standard_policy,
                grant_references=await state.grant_references(),
                draft_owner_id=operator_id,
                idempotency_key=idempotency_key,
                expires_at=datetime.now(UTC).replace(tzinfo=None) + timedelta(minutes=30),
            )
        )
    await state.bind_draft_authorization_release(
        draft_id=reservation.release_id,
        authorization_release_id=target_release_id,
    )
    outcome = await service.publish(
        draft_id=reservation.release_id,
        expected_current_release_id=current.catalog_id,
        idempotency_key=idempotency_key,
    )
    _require(outcome.status == "CURRENT", "Authorization Model Catalog cutover did not finalize")
    return outcome.release_id


async def execute(args: argparse.Namespace, *, live_settings: Any = settings) -> int:
    await initialize_app_context(config=_offline_settings(live_settings))
    source_client: FGAClient | None = None
    target_client: FGAClient | None = None
    try:
        current = await _load_current_release()
        config = live_settings.openfga
        current_pin = await discover_openfga_runtime(
            config,
            expected_model=None,
            allow_bootstrap=False,
            required_store_id=current.store_id,
            required_model_id=current.model_id,
        )
        _require(current_pin.model_checksum == current.model_checksum, "CURRENT SQL model checksum differs from OpenFGA")
        latest_pin = await discover_openfga_runtime(
            config,
            expected_model=None,
            allow_bootstrap=False,
            required_store_id=current.store_id,
        )
        source_client = FGAClient(
            api_url=config.api_url,
            store_id=current.store_id,
            model_id=current.model_id,
            timeout=config.timeout,
        )
        target_model = get_authorization_model_f048()
        target_checksum = authorization_model_checksum(target_model)
        target_model_id = await _find_remote_model_id(source_client, target_checksum)
        report = PublishReport(
            mode="apply" if args.apply else "dry-run",
            environment=current.environment,
            store_id=current.store_id,
            current_catalog_id=current.catalog_id,
            current_model_id=current.model_id,
            current_model_checksum=current.model_checksum,
            latest_openfga_model_id=latest_pin.model_id,
            latest_openfga_model_checksum=latest_pin.model_checksum,
            target_model_id=target_model_id,
            target_model_checksum=target_checksum,
            model_version=MODEL_VERSION,
            catalog_write_fenced=current.write_fenced,
            needs_model_publish=target_model_id is None,
            needs_catalog_cutover=current.model_checksum != target_checksum,
        )
        print(json.dumps(asdict(report), ensure_ascii=False, sort_keys=True))
        if not args.apply:
            print("[dry-run] no SQL, OpenFGA, or Catalog mutations were requested")
            return EXIT_OK

        _require(args.confirm_store_id == current.store_id, "--confirm-store-id does not match the discovered Store")
        _require(
            args.confirm_target_model_checksum == target_checksum,
            "--confirm-target-model-checksum does not match the code-generated model",
        )
        _require(not current.write_fenced, "CURRENT Catalog is write fenced")
        await _assert_apply_window()
        if current.model_checksum == target_checksum:
            print(
                json.dumps(
                    {
                        "event": "already_current",
                        "catalog_release_id": current.catalog_id,
                        "store_id": current.store_id,
                        "model_id": current.model_id,
                        "model_checksum": current.model_checksum,
                    },
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )
            return EXIT_OK

        if target_model_id is None:
            publisher = OpenFGAMigrationModelPublisher(
                source_client=source_client,
                environment=_environment_name(live_settings.environment),
                predecessor_model_id=current.model_id,
            )
            target_model_id = await publisher.aget_or_publish(
                store_id=current.store_id,
                model=target_model,
                checksum=target_checksum,
            )
        target_client = source_client.for_model(target_model_id)
        target_release_id = await _authorization_release_id(
            current.environment,
            current.store_id,
            target_model_id,
        )
        await _activate_model_release(target_release_id)
        new_catalog_id = await _publish_noop_catalog_cutover(
            current=current,
            target_client=target_client,
            target_release_id=target_release_id,
            operator_id=args.operator_id,
            target_checksum=target_checksum,
        )
        final = await _load_current_release()
        _require(
            final.catalog_id == new_catalog_id
            and final.store_id == current.store_id
            and final.model_id == target_model_id
            and final.model_checksum == target_checksum,
            "final CURRENT Catalog/model pin verification failed",
        )
        await _retire_other_active_models(final)
        print(
            json.dumps(
                {
                    "event": "authorization_model_change_published",
                    "catalog_release_id": final.catalog_id,
                    "store_id": final.store_id,
                    "model_id": final.model_id,
                    "model_checksum": final.model_checksum,
                    "model_version": MODEL_VERSION,
                },
                ensure_ascii=False,
                sort_keys=True,
            )
        )
        return EXIT_OK
    finally:
        if target_client is not None and target_client is not source_client:
            await target_client.close()
        if source_client is not None:
            await source_client.close()
        await close_app_context()


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        return asyncio.run(execute(args))
    except AuthorizationModelPublishBlockedError as exc:
        print(f"Authorization model publish blocked: {exc}", file=sys.stderr)
        return EXIT_BLOCKED
    except Exception:
        traceback.print_exc()
        return EXIT_RUNTIME_ERROR


if __name__ == "__main__":
    sys.exit(main())
