export const ERROR_CODES = {
    "10400": "error_assistant_not_found",
    "10401": "error_assistant_online_failed",
    "10402": "error_assistant_name_duplicate",
    "10403": "error_assistant_online_cannot_edit",
    "10410": "error_tool_name_exists",
    "10411": "error_tool_api_empty",
    "10412": "error_tool_not_found",
    "10413": "error_preset_tool_category_cannot_delete",
    "403": "error_no_permission",
    "404": "error_resource_not_found",
    "503": "error_service_busy",
    "10300": "error_component_exists",
    "10301": "error_component_not_found",
    "10100": "error_create_training_task_failed",
    "10101": "error_training_set_required",
    "10102": "error_task_not_found",
    "10103": "error_task_status_error",
    "10104": "error_task_cancel_failed",
    "10105": "error_task_delete_failed",
    "10106": "error_task_publish_failed",
    "10107": "error_model_name_interface_modify_failed",
    "10108": "error_cancel_publish_failed",
    "10109": "error_invalid_training_params",
    "10110": "error_model_name_exists",
    "10120": "error_training_file_not_found",
    "10125": "error_get_gpu_info_failed",
    "10126": "error_get_model_list_failed",
    "10500": "error_skill_version_not_found",
    "10501": "error_current_version_cannot_delete",
    "10502": "error_version_name_exists",
    "10503": "error_skill_name_duplicate",
    "10520": "error_skill_not_found",
    "10521": "error_skill_online_cannot_edit",
    "10525": "error_workflow_online_cannot_edit",
    "10529": "error_workflow_name_duplicate",
    "10530": "error_template_name_exists",
    "10900": "error_knowledge_base_name_duplicate",
    "10901": "error_knowledge_base_embedding_required",
    "10910": "error_knowledge_base_version_segmentation_not_supported",
    "10800": "error_model_provider_name_duplicate",
    "10801": "error_model_duplicate",
    "10700": "error_tag_exists",
    "10701": "error_tag_not_found",
    "10600": "error_account_password_error",
    "10601": "error_password_expired",
    "10602": "error_password_not_set",
    "10603": "error_current_password_error",
    "10604": "error_account_logged_in_another_device",
    "10605": "error_username_exists",
    "10606": "error_user_group_role_required",
    "10610": "error_user_group_has_users_cannot_delete",
    "10920": "error_qa_knowledge_base_model_not_configured",
    "10930": "error_question_exists",
    "10527": "error_workflow_user_input_timeout",
    "10528": "error_node_execution_exceeded_max_times",
    "10531": "error_function_upgraded_need_recreate",
    "10532": "error_workflow_version_upgraded",
    "10540": "error_server_threads_full",

    "10001": "error_sft_service_not_found",
    "10002": "error_invalid_operation",
    "10003": "error_resource_download_failed",
    "10004": "error_embedding_model_not_configured",
    "10005": "error_embedding_model_not_found",
    "10006": "error_embedding_model_type_mismatch",
    "10007": "error_check_vector_search_model_status",
    "10008": "error_llm_model_configuration_missing",
    "10009": "error_llm_model_configuration_deleted",
    "10010": "error_model_provider_configuration_deleted",
    "10011": "error_model_type_not_supported",
    "10012": "error_model_offline",
    "10013": "error_llm_initialization_failed",
    "10200": "error_model_not_found",
    "10420": "error_assistant_deleted",
    "10421": "error_assistant_not_online",
    "10422": "error_assistant_inference_model_empty",
    "10423": "error_assistant_inference_model_not_configured",
    "10499": "error_assistant_service_exception",
    "10526": "error_workflow_initialization_failed",
    "10802": "error_service_provider_add_failure",
    "10803": "error_service_provider_add_partial_failure",
    "10940": "error_file_being_parsed_not_copyable",
    "10950": "error_multiple_files_deletion_not_supported",
    "10951": "error_knowledge_base_rebuilding_not_editable",
    "11010": "error_sop_file_format_invalid",
    "11020": "error_linsight_file_upload_failed",
    "11030": "error_linsight_usage_limit_exceeded",
    "11040": "error_submit_linsight_user_problem_failed",
    "11050": "error_check_vector_search_model_status",
    "11060": "error_guidance_manual_search_failed",
    "11070": "error_guidance_manual_query_failed",
    "11080": "error_linsight_tool_initialization_failed",
    "11090": "error_linsight_bisheng_llm_related_error",
    "11100": "error_generate_sop_content_failed",
    "11110": "error_modify_sop_content_failed",
    "11120": "error_linsight_session_version_conflict",
    "11130": "error_start_linsight_task_failed",
    "11140": "error_get_linsight_queue_status_failed",
    "11150": "error_add_guidance_manual_failed",
    "11160": "error_update_guidance_manual_failed",
    "11170": "error_delete_guidance_manual_failed",
    "12040": "error_web_search_tool_not_found",
    "12041": "error_session_not_found",
    "12042": "error_agent_already_added",
    "13001": "error_skill_deleted",
    "13002": "error_skill_not_online",
    "13003": "error_skill_not_compiled",
    "13004": "error_chat_service_exception",
    "13005": "error_llm_skill_execution_error",
    "13006": "error_document_parse_failure",
    "13007": "error_input_data_parse_fail",
    "14001": "error_backend_processing_try_later"
} as const

/**
 * 获取错误信息的国际化键值
 * @param errorCode 错误码
 * @returns 对应的国际化键值
 */
export const getErrorI18nKey = (errorCode: string): string => {
    return ERROR_CODES[errorCode as keyof typeof ERROR_CODES] || 'error_unknown'
}

/**
 * 错误码类型
 */
export type ErrorCode = keyof typeof ERROR_CODES