class MDX_STYLE:
    PLAIN_TEXT = "Normal"
    PLAIN_LIST = "List"
    LIST_NUMBER = "List Number"
    LIST_CONTINUE = "List Continue"
    LIST_BULLET = "List Bullet"
    BLOCKQUOTE = "Quote"
    HEADING = "Heading"
    TABLE = "Table Grid"
    CAPTION = "Caption"
