{{- if not .Values.token.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bisheng-sandbox.fullname" . }}
  labels:
    {{- include "bisheng-sandbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token.value | quote }}
{{- end }}
