from datetime import datetime
from typing import Optional

from sqlalchemy import Column, DateTime, text
from sqlmodel import Field

from bisheng.common.models.base import SQLModelSerializable


class ReportBase(SQLModelSerializable):
    # ```
    # Useflow_id Path to get the latest template in reverse order by update time
    # Records of the final report generated by the template are stored`
    flow_id: str = Field(index=False, description='Skill name')
    file_name: Optional[str] = Field(default=None, index=False, description='Generate Report Name')
    template_name: Optional[str] = Field(default=None, index=False, description='Report Template Data Storage Path')
    version_key: Optional[str] = Field(default=None, index=True, unique=True, description='Frontend Template Uniquekey')
    newversion_key: Optional[str] = Field(index=False, default=None, description='Frontend Template Nextkey')
    object_name: Optional[str] = Field(default=None, index=False, description='Report Template Data Storage Path')
    del_yn: Optional[int] = Field(index=False, default=0, description='Delete Status 1Show Delete')
    create_time: Optional[datetime] = Field(default=None, sa_column=Column(
        DateTime, nullable=False, index=True, server_default=text('CURRENT_TIMESTAMP')))
    update_time: Optional[datetime] = Field(default=None, sa_column=Column(
        DateTime, nullable=False, server_default=text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')))


class Report(ReportBase, table=True):
    __tablename__ = 't_report'
    id: Optional[int] = Field(default=None, primary_key=True)


class ReportRead(ReportBase):
    id: Optional[int] = None


class RoleUpdate(ReportBase):
    role_name: Optional[str] = None
    remark: Optional[str] = None


class RoleCreate(ReportBase):
    pass
