import asyncio
from typing import Union

from fastapi import APIRouter, Body, Request, Response
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from bisheng.api.v1.schema.chat_schema import APIChatCompletion
from bisheng.api.v1.schemas import resp_200
from bisheng.common.errcode.http_error import UnAuthorizedError
from bisheng.core.context.tenant import bypass_tenant_filter_if
from bisheng.database.models.message import ChatMessageDao
from bisheng.database.models.session import MessageSessionDao
from bisheng.llm.domain.services.model_rate_limit import RecoveryAction, RecoveryCommand
from bisheng.llm.domain.services.model_recovery_service import (
    ModelRecoveryService,
    RecoveryNotAllowedError,
    build_recovery_rejected_sse,
)
from bisheng.workstation.domain.schemas import WorkstationMessage
from bisheng.workstation.domain.services.chat_helpers import (
    _convert_legacy_message,
    _drop_legacy_sibling_branches,
    _format_new_message,
    _is_new_format,
)

from ...domain.services.chat_service import (
    DailyChatRecoveryPort,
    DailyChatRecoveryService,
    stream_chat_completion,
)
from ..dependencies import LoginUserDep, ShareLink, ShareLinkDep

router = APIRouter()


class DailyChatRecoveryRequest(BaseModel):
    attempt_id: str
    subject_id: str
    action: RecoveryAction
    target_model_id: int | None = None


@router.post("/gen_title")
async def gen_title(conversationId: str = Body(..., embed=True), login_user=LoginUserDep):
    # The title is generated by a background task kicked off when the chat round
    # ends, so it isn't ready the instant the frontend polls. Wait until a real
    # name lands (slow models take well over the old fixed 5s) instead of racing
    # it — poll the session name up to a deadline, returning as soon as it's set.
    deadline_s = 30.0
    interval_s = 0.5
    waited = 0.0
    name = None
    while waited < deadline_s:
        session = await MessageSessionDao.async_get_one(conversationId)
        name = session.name if session else None
        # "New Chat" is the legacy stored placeholder — new rows store "" and the
        # client renders the localized placeholder itself.
        if name and name != "New Chat":
            break
        await asyncio.sleep(interval_s)
        waited += interval_s
    return resp_200(data={"title": name if name and name != "New Chat" else ""})


@router.get("/messages/{conversationId}")
async def get_chat_history(
    conversationId: str,
    login_user=LoginUserDep,
    share_link: Union[ShareLink, None] = ShareLinkDep,
):
    with bypass_tenant_filter_if(share_link is not None):
        messages = await ChatMessageDao.aget_messages_by_chat_id(chat_id=conversationId, limit=1000)
    if not messages:
        return resp_200([])
    if login_user.user_id != messages[0].user_id:
        if not share_link or share_link.resource_id != conversationId:
            return UnAuthorizedError.return_resp()
    return resp_200([await WorkstationMessage.from_chat_message(message) for message in messages])


@router.get("/messages/{conversationId}/agent")
async def get_agent_chat_history(
    conversationId: str,
    login_user=LoginUserDep,
    share_link: Union[ShareLink, None] = ShareLinkDep,
):
    """v2.5: return chat history in the new ChatResponse (Agent-mode) shape.

    - Legacy regenerate sibling branches are collapsed: only the latest
      `create_time` answer per `parentMessageId` survives (R10 / A2).
    - Legacy plain-text answers are converted on-the-fly to JSON shape
      (thinking / web tool_calls extracted from `:::` markers).
    - New Agent-mode messages pass through.
    """
    with bypass_tenant_filter_if(share_link is not None):
        messages = await ChatMessageDao.aget_messages_by_chat_id(chat_id=conversationId, limit=1000)
    if not messages:
        return resp_200([])
    if login_user.user_id != messages[0].user_id:
        if not share_link or share_link.resource_id != conversationId:
            return UnAuthorizedError.return_resp()

    # 1. Drop legacy sibling branches (keep only latest per parentMessageId)
    messages = _drop_legacy_sibling_branches(messages)

    # 2. Map each row through the appropriate formatter
    result = []
    for msg in messages:
        if _is_new_format(msg):
            result.append(_format_new_message(msg))
        else:
            result.append(_convert_legacy_message(msg))
    return resp_200(result)


@router.post("/chat/completions")
async def chat_completions(
    request: Request,
    data: APIChatCompletion,
    login_user=LoginUserDep,
):
    return await stream_chat_completion(request, data, login_user)


@router.post("/chat/executions/{execution_id}/recover")
async def recover_chat_execution(
    execution_id: str,
    data: DailyChatRecoveryRequest,
    request: Request,
    login_user=LoginUserDep,
):
    command = RecoveryCommand(
        execution_id=execution_id,
        attempt_id=data.attempt_id,
        subject_id=data.subject_id,
        action=data.action,
        target_model_id=data.target_model_id,
    )
    recovery_service = ModelRecoveryService()
    try:
        result = await DailyChatRecoveryService(
            recovery_service=recovery_service,
            port_factory=lambda user: DailyChatRecoveryPort(user, request),
        ).recover(command, login_user=login_user)
    except RecoveryNotAllowedError:
        return StreamingResponse(
            iter([build_recovery_rejected_sse(command)]),
            media_type="text/event-stream",
        )
    if isinstance(result.payload, StreamingResponse):
        result.payload.body_iterator = recovery_service.release_lock_after_stream(
            result.payload.body_iterator,
            result.attempt,
            tenant_id=login_user.tenant_id,
            user_id=login_user.user_id,
        )
        return result.payload
    if isinstance(result.payload, Response):
        await recovery_service.release_recovery_lock(
            result.attempt,
            tenant_id=login_user.tenant_id,
            user_id=login_user.user_id,
        )
        return result.payload
    return StreamingResponse(
        iter([build_recovery_rejected_sse(result.attempt)]),
        media_type="text/event-stream",
    )
