"""门户全文索引基础层固定参数。

这些值属于全文投影实现，不是通用知识库运行时配置。修改后需要重新发布
应用与 Worker，不支持通过 Settings、数据库配置或 Redis 热更新。
"""

KNOWLEDGE_FULLTEXT_INDEX_ALIAS = "knowledge_fulltext"
KNOWLEDGE_FULLTEXT_INDEX_PREFIX = "knowledge_fulltext"
KNOWLEDGE_FULLTEXT_INDEX_SCHEMA_VERSION = 1
KNOWLEDGE_FULLTEXT_INDEX_SHARDS = 1
KNOWLEDGE_FULLTEXT_INDEX_REPLICAS = 0
KNOWLEDGE_FULLTEXT_NGRAM_MIN = 1
KNOWLEDGE_FULLTEXT_NGRAM_MAX = 20

# 门户高级检索只读查询参数。
KNOWLEDGE_FULLTEXT_SEARCH_BATCH_SIZE = 100
KNOWLEDGE_FULLTEXT_SEARCH_MAX_SCAN_HITS = 1000
KNOWLEDGE_FULLTEXT_SEARCH_PIT_KEEP_ALIVE = "2m"
KNOWLEDGE_FULLTEXT_SEARCH_READINESS_TTL_SECONDS = 60.0
KNOWLEDGE_FULLTEXT_SEARCH_REQUEST_TIMEOUT_SECONDS = 10.0
KNOWLEDGE_FULLTEXT_SEARCH_UPLOADER_CANDIDATE_LIMIT = 100
KNOWLEDGE_FULLTEXT_SEARCH_UPLOADER_SUPPORT_LIMIT = 5
KNOWLEDGE_FULLTEXT_SEARCH_UPLOADER_RESULT_LIMIT = 20
KNOWLEDGE_FULLTEXT_SEARCH_MAX_CONDITIONS = 20
KNOWLEDGE_FULLTEXT_SEARCH_FIELD_BOOSTS = {
    "file_name": 5.0,
    "display_title": 5.0,
    "tags": 3.0,
    "summary": 2.0,
    "content": 1.0,
}

KNOWLEDGE_FULLTEXT_CHUNK_PAGE_SIZE = 500
KNOWLEDGE_FULLTEXT_FANOUT_BATCH_SIZE = 200
KNOWLEDGE_FULLTEXT_DISPATCH_BATCH_SIZE = 100
KNOWLEDGE_FULLTEXT_DISPATCH_INTERVAL_SECONDS = 300.0
KNOWLEDGE_FULLTEXT_DISPATCH_TASK = "bisheng.worker.knowledge.fulltext_index.dispatch"
KNOWLEDGE_FULLTEXT_MAX_RETRIES = 8
KNOWLEDGE_FULLTEXT_RETRY_BASE_SECONDS = 300
KNOWLEDGE_FULLTEXT_RETRY_MAX_SECONDS = 1800
KNOWLEDGE_FULLTEXT_DB_RETRY_MAX_ATTEMPTS = 3
KNOWLEDGE_FULLTEXT_DB_RETRY_BASE_SECONDS = 0.05
KNOWLEDGE_FULLTEXT_DB_RETRY_MAX_SECONDS = 0.6
KNOWLEDGE_FULLTEXT_LEASE_TTL_SECONDS = 600
KNOWLEDGE_FULLTEXT_MAX_OVERLAP_CHARS = 1000
KNOWLEDGE_FULLTEXT_AUTO_REPAIR_MAX_ATTEMPTS = 1
KNOWLEDGE_FULLTEXT_AUTO_REPAIR_NOT_READY_FAILURES = 2
KNOWLEDGE_FULLTEXT_AUTO_REPAIR_BATCH_SIZE = 100
KNOWLEDGE_FULLTEXT_AUTO_REPAIR_LEASE_SECONDS = 960
KNOWLEDGE_FULLTEXT_AUTO_REPAIR_TASK = "bisheng.worker.knowledge.fulltext_index.repair_source"

KNOWLEDGE_FULLTEXT_ENGAGEMENT_DELAY_SECONDS = 300
KNOWLEDGE_FULLTEXT_ENGAGEMENT_BATCH_SIZE = 200
KNOWLEDGE_FULLTEXT_ENGAGEMENT_LEASE_SECONDS = 600
KNOWLEDGE_FULLTEXT_ENGAGEMENT_RECONCILE_DAYS = 3
KNOWLEDGE_FULLTEXT_ENGAGEMENT_HISTORY_PAGE_SIZE = 500
KNOWLEDGE_FULLTEXT_ENGAGEMENT_HISTORY_LOCK_SECONDS = 4000
KNOWLEDGE_FULLTEXT_ENGAGEMENT_SYNC_TASK = "bisheng.worker.knowledge.fulltext_engagement.sync"
KNOWLEDGE_FULLTEXT_ENGAGEMENT_REBUILD_TASK = "bisheng.worker.knowledge.fulltext_engagement.rebuild"
KNOWLEDGE_FULLTEXT_ENGAGEMENT_RECONCILE_TASK = "bisheng.worker.knowledge.fulltext_engagement.reconcile"
KNOWLEDGE_FULLTEXT_ENGAGEMENT_DAILY_INDEX = "mid_knowledge_space_content_stat"
KNOWLEDGE_FULLTEXT_ENGAGEMENT_RAW_INDEX = "base_telemetry_events"


def physical_index_name() -> str:
    return f"{KNOWLEDGE_FULLTEXT_INDEX_PREFIX}_v{KNOWLEDGE_FULLTEXT_INDEX_SCHEMA_VERSION}"


def ensure_runtime_compatible(*, multi_tenant_enabled: bool) -> None:
    if multi_tenant_enabled:
        raise ValueError(
            "knowledge fulltext index is not compatible with multi-tenant mode; "
            "redesign document IDs and isolation before deployment"
        )
