"""
Article ES CRUD Service

Encapsulates all operations on ES article index: index, bulk index, get, update, delete, search.
All methods are async, using get_es_connection to obtain AsyncElasticsearch client.
"""
import logging
from typing import List, Optional, Dict, Any

from elasticsearch import AsyncElasticsearch, helpers as es_helpers

from bisheng.channel.domain.es.article_index import (
    ARTICLE_INDEX_NAME,
    ensure_article_index_exists, ensure_article_index_exists_sync,
)
from bisheng.channel.domain.schemas.article_schema import (
    ArticleDocument,
    ArticleSearchResultItem,
    ArticleSearchPageResponse, ArticleDetailResponse,
)
from bisheng.core.search.elasticsearch.manager import get_es_connection, get_es_connection_sync

logger = logging.getLogger(__name__)


class ArticleEsService:
    """Article ES Service, encapsulates all operations on channel_articles index"""

    def __init__(self):
        self._es_client: Optional[AsyncElasticsearch] = None

    async def _get_client(self) -> AsyncElasticsearch:
        """Get ES client, lazy loading"""
        if self._es_client is None:
            self._es_client = await get_es_connection()
        return self._es_client

    async def ensure_index(self) -> None:
        """Ensure article index exists"""
        client = await self._get_client()
        await ensure_article_index_exists(client)

    @staticmethod
    def ensure_index_sync() -> None:
        """Ensure article index exists (synchronous method)"""
        client = get_es_connection_sync()
        ensure_article_index_exists_sync(client)

    # ──────────────────────────────────────────
    #  Create
    # ──────────────────────────────────────────

    async def index_article(self, article: ArticleDocument, doc_id: Optional[str] = None) -> str:
        """
        Index a single article.

        Args:
            article: Article document
            doc_id: Optional document ID, auto-generated by ES if not provided

        Returns:
            Document ID
        """
        client = await self._get_client()
        body = article.model_dump(mode='json')

        kwargs: Dict[str, Any] = {
            "index": ARTICLE_INDEX_NAME,
            "body": body,
        }
        if doc_id:
            kwargs["id"] = doc_id

        result = await client.index(**kwargs)
        return result["_id"]

    async def bulk_index_articles(self, articles: List[ArticleDocument],
                                  doc_ids: Optional[List[str]] = None) -> int:
        """
        Bulk index articles.

        Args:
            articles: Article list
            doc_ids: Optional document ID list, length must match articles

        Returns:
            Number of successfully indexed documents
        """
        if not articles:
            return 0

        client = await self._get_client()
        actions = []
        for i, article in enumerate(articles):
            action = {
                "_index": ARTICLE_INDEX_NAME,
                "_source": article.model_dump(mode='json'),
            }
            if doc_ids and i < len(doc_ids) and doc_ids[i]:
                action["_id"] = doc_ids[i]
            actions.append(action)

        success, errors = await es_helpers.async_bulk(client, actions, raise_on_error=False)
        if errors:
            logger.warning(f"Bulk index completed with {len(errors)} errors: {errors[:3]}")
        return success

    @staticmethod
    def bulk_index_articles_sync(articles: List[ArticleDocument],
                                 doc_ids: Optional[List[str]] = None) -> int:
        """Synchronous version: Bulk index articles."""
        if not articles:
            return 0
        client = get_es_connection_sync()
        actions = []
        for i, article in enumerate(articles):
            action = {
                "_index": ARTICLE_INDEX_NAME,
                "_source": article.model_dump(mode='json'),
            }
            if doc_ids and i < len(doc_ids) and doc_ids[i]:
                action["_id"] = doc_ids[i]
            actions.append(action)
        success, errors = es_helpers.bulk(client, actions, raise_on_error=False)
        if errors:
            logger.warning(f"Bulk index completed with {len(errors)} errors: {errors[:3]}")
        return success

    # ──────────────────────────────────────────
    #  Read
    # ──────────────────────────────────────────

    async def get_article(self, doc_id: str) -> Optional[ArticleDetailResponse]:
        """
        Get article by document ID.

        Args:
            doc_id: ES document ID

        Returns:
            Article search result item, returns None if not found
        """
        client = await self._get_client()
        try:
            result = await client.get(index=ARTICLE_INDEX_NAME, id=doc_id)
            source = result["_source"]
            return ArticleDetailResponse(doc_id=result["_id"], **source)
        except Exception:
            logger.debug(f"Article not found: {doc_id}")
            return None

    # ──────────────────────────────────────────
    #  Update
    # ──────────────────────────────────────────

    async def update_article(self, doc_id: str, updates: Dict[str, Any]) -> bool:
        """
        Partially update article fields.

        Args:
            doc_id: ES document ID
            updates: Dictionary of fields to update

        Returns:
            Whether successful
        """
        client = await self._get_client()
        try:
            await client.update(
                index=ARTICLE_INDEX_NAME,
                id=doc_id,
                body={"doc": updates},
            )
            return True
        except Exception as e:
            logger.error(f"Failed to update article {doc_id}: {e}")
            return False

    # ──────────────────────────────────────────
    #  Delete
    # ──────────────────────────────────────────

    async def delete_article(self, doc_id: str) -> bool:
        """
        Delete article.

        Args:
            doc_id: ES document ID

        Returns:
            Whether successful
        """
        client = await self._get_client()
        try:
            await client.delete(index=ARTICLE_INDEX_NAME, id=doc_id)
            return True
        except Exception as e:
            logger.error(f"Failed to delete article {doc_id}: {e}")
            return False

    # ──────────────────────────────────────────
    #  Search & Count
    # ──────────────────────────────────────────

    def _build_count_query(
            self,
            source_ids: Optional[List[str]] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
            include_article_ids: Optional[List[str]] = None,
    ) -> Optional[Dict[str, Any]]:
        """Build count query, returns None if result is definitively 0"""
        must_clauses = []
        must_not_clauses = []
        filter_clauses = []

        if source_ids is not None:
            if not source_ids:
                return None
            filter_clauses.append({"terms": {"source_id": source_ids}})

        if include_article_ids is not None:
            if not include_article_ids:
                return None
            filter_clauses.append({"terms": {"_id": include_article_ids}})

        if filter_rules:
            for rule in filter_rules:
                rule_type = rule.get("rule_type")
                keywords = rule.get("keywords", [])
                relation = rule.get("relation", "or")

                if not keywords:
                    continue

                keyword_queries = []
                for kw in keywords:
                    keyword_queries.append({
                        "multi_match": {
                            "query": kw,
                            "fields": ["title", "content"],
                            "type": "best_fields",
                        }
                    })

                if relation == "and":
                    combined = {"bool": {"must": keyword_queries}}
                else:
                    combined = {"bool": {"should": keyword_queries, "minimum_should_match": 1}}

                if rule_type == "include":
                    must_clauses.append(combined)
                elif rule_type == "exclude":
                    must_not_clauses.append(combined)

        bool_query: Dict[str, Any] = {}
        if must_clauses:
            bool_query["must"] = must_clauses
        if must_not_clauses:
            bool_query["must_not"] = must_not_clauses
        if filter_clauses:
            bool_query["filter"] = filter_clauses

        if bool_query:
            return {"bool": bool_query}
        else:
            return {"match_all": {}}

    async def count_articles(
            self,
            source_ids: Optional[List[str]] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
            include_article_ids: Optional[List[str]] = None,
    ) -> int:
        """
        Count articles, supports source filtering, filter rules, and article ID list inclusion.
        """
        query = self._build_count_query(source_ids, filter_rules, include_article_ids)
        if query is None:
            return 0

        client = await self._get_client()
        response = await client.count(index=ARTICLE_INDEX_NAME, query=query)
        return response["count"]

    async def count_articles_batch(
            self,
            requests: List[Dict[str, Any]]
    ) -> List[int]:
        """
        Batch count articles.
        requests is a list of dictionaries, each containing parameters for count_articles:
        - source_ids
        - filter_rules
        - include_article_ids
        """
        if not requests:
            return []

        client = await self._get_client()
        body = []
        zero_indices = set()
        
        for i, req in enumerate(requests):
            query = self._build_count_query(
                source_ids=req.get("source_ids"),
                filter_rules=req.get("filter_rules"),
                include_article_ids=req.get("include_article_ids")
            )
            if query is None:
                zero_indices.add(i)
                # msearch requires valid query even if we know it's zero to maintain order easily
                body.append({"index": ARTICLE_INDEX_NAME})
                body.append({"query": {"match_none": {}}, "size": 0})
            else:
                body.append({"index": ARTICLE_INDEX_NAME})
                body.append({"query": query, "size": 0})

        response = await client.msearch(body=body)
        
        counts = []
        for i, r in enumerate(response["responses"]):
            if i in zero_indices:
                counts.append(0)
            else:
                total = r["hits"]["total"]
                counts.append(total["value"] if isinstance(total, dict) else total)
        return counts

    async def search_articles(
            self,
            source_ids: Optional[List[str]] = None,
            keyword: Optional[str] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
            page: int = 1,
            page_size: int = 20,
            exclude_article_ids: Optional[List[str]] = None,
    ) -> ArticleSearchPageResponse:
        """
        Search articles, supports source filtering, keyword search, filter rules, highlighting, and pagination.

        Args:
            source_ids: Source ID list filter
            keyword: Search keyword (matches title, content, source ID)
            filter_rules: Channel filter rules list
                          Each rule format: {"rule_type": "include"/"exclude",
                                        "keywords": [...], "relation": "and"/"or"}
            page: Page number (starts from 1)
            page_size: Page size
            exclude_article_ids: List of article IDs to exclude

        Returns:
            ArticleSearchPageResponse
        """
        client = await self._get_client()

        # Build bool query
        must_clauses = []
        must_not_clauses = []
        filter_clauses = []

        # 1. Source ID filtering
        if source_ids:
            filter_clauses.append({
                "terms": {"source_id": source_ids}
            })

        # 1.5 Exclude specified article IDs
        if exclude_article_ids:
            must_not_clauses.append({
                "terms": {"_id": exclude_article_ids}
            })

        # 2. Keyword search (title + content + source ID)
        if keyword:
            must_clauses.append({
                "multi_match": {
                    "query": keyword,
                    "fields": ["title^3", "content", "source_id"],
                    "type": "best_fields",
                }
            })

        # 3. Channel filter rules
        if filter_rules:
            for rule in filter_rules:
                rule_type = rule.get("rule_type")
                keywords = rule.get("keywords", [])
                relation = rule.get("relation", "or")

                if not keywords:
                    continue

                # Build keyword matching subquery
                keyword_queries = []
                for kw in keywords:
                    keyword_queries.append({
                        "multi_match": {
                            "query": kw,
                            "fields": ["title", "content"],
                            "type": "best_fields",
                        }
                    })

                if relation == "and":
                    combined = {"bool": {"must": keyword_queries}}
                else:
                    combined = {"bool": {"should": keyword_queries, "minimum_should_match": 1}}

                if rule_type == "include":
                    must_clauses.append(combined)
                elif rule_type == "exclude":
                    must_not_clauses.append(combined)

        # Assemble complete query
        bool_query: Dict[str, Any] = {}
        if must_clauses:
            bool_query["must"] = must_clauses
        if must_not_clauses:
            bool_query["must_not"] = must_not_clauses
        if filter_clauses:
            bool_query["filter"] = filter_clauses

        if bool_query:
            query = {"bool": bool_query}
        else:
            query = {"match_all": {}}

        # Highlighting configuration
        highlight_config = {}
        if keyword:
            highlight_config = {
                "pre_tags": ["<em>"],
                "post_tags": ["</em>"],
                "fields": {
                    "title": {"number_of_fragments": 0},
                    "content": {"fragment_size": 200, "number_of_fragments": 3},
                },
            }

        # Build request body
        from_offset = (page - 1) * page_size
        body: Dict[str, Any] = {
            "query": query,
            "sort": [{"update_time": {"order": "desc"}}],
            "from": from_offset,
            "size": page_size,
            "_source": {
                "excludes": ["content_html"]  # Exclude content_html field by default to reduce network transfer and parsing overhead
             }
        }
        if highlight_config:
            body["highlight"] = highlight_config

        # Execute search
        response = await client.search(index=ARTICLE_INDEX_NAME, body=body)

        # Parse results
        total = response["hits"]["total"]
        if isinstance(total, dict):
            total_count = total["value"]
        else:
            total_count = total

        items = []
        for hit in response["hits"]["hits"]:
            source = hit["_source"]
            highlight = hit.get("highlight")

            item = ArticleSearchResultItem(
                doc_id=hit["_id"],
                score=hit.get("_score"),
                highlight=highlight,
                **source,
            )
            items.append(item)

        return ArticleSearchPageResponse(
            data=items,
            total=total_count,
            page=page,
            page_size=page_size,
        )

    @staticmethod
    def get_source_latest_article_time_sync(source_id: str) -> Optional[str]:
        """Get source's latest article update time (synchronous method)"""
        client = get_es_connection_sync()
        body = {
            "size": 1,
            "query": {
                "term": {"source_id": source_id}
            },
            "sort": [{"create_time": {"order": "desc"}}],
            "_source": ["create_time"],
        }
        response = client.search(index=ARTICLE_INDEX_NAME, body=body)
        hits = response["hits"]["hits"]
        if hits:
            return hits[0]["_source"]["create_time"]
        return None
