"""
Article ES CRUD Service

Encapsulates all operations on ES article index: index, bulk index, get, update, delete, search.
All methods are async, using get_es_connection to obtain AsyncElasticsearch client.
"""
import logging
from typing import List, Optional, Dict, Any, Tuple

from elasticsearch import AsyncElasticsearch, helpers as es_helpers

from bisheng.channel.domain.es.article_index import (
    ARTICLE_INDEX_NAME,
    ensure_article_index_exists, ensure_article_index_exists_sync,
)
from bisheng.channel.domain.schemas.article_schema import (
    ArticleDocument,
    ArticleSearchResultItem,
    ArticleSearchPageResponse, ArticleDetailResponse,
)
from bisheng.core.search.elasticsearch.manager import get_es_connection, get_es_connection_sync

logger = logging.getLogger(__name__)


class ArticleEsService:
    """Article ES Service, encapsulates all operations on channel_articles index"""

    CONTENT_PREVIEW_MAX_LENGTH = 256

    def __init__(self):
        self._es_client: Optional[AsyncElasticsearch] = None

    async def _get_client(self) -> AsyncElasticsearch:
        """Get ES client, lazy loading"""
        if self._es_client is None:
            self._es_client = await get_es_connection()
        await self.ensure_index()
        return self._es_client

    async def ensure_index(self) -> None:
        """Ensure article index exists"""
        if self._es_client is None:
            self._es_client = await get_es_connection()
        await ensure_article_index_exists(self._es_client)

    @staticmethod
    def ensure_index_sync() -> None:
        """Ensure article index exists (synchronous method)"""
        client = get_es_connection_sync()
        ensure_article_index_exists_sync(client)

    @staticmethod
    def refresh_index_sync() -> None:
        """Force an ES refresh on the article index so freshly-indexed docs are
        immediately visible to GET / search. Used by the Celery worker right
        after bulk_index to avoid the 'Article not found' race when the
        knowledge-space sync hook reads the same docs back."""
        try:
            client = get_es_connection_sync()
            client.indices.refresh(index=ARTICLE_INDEX_NAME)
        except Exception as e:  # pragma: no cover — best-effort
            logger.warning(f"ES refresh failed for {ARTICLE_INDEX_NAME}: {e}")

    @classmethod
    def _build_content_preview(cls, content: Optional[str]) -> str:
        """Build a truncated content preview for search list responses."""
        if not content:
            return ""
        return content[:cls.CONTENT_PREVIEW_MAX_LENGTH]

    @classmethod
    def _build_article_body(cls, article: ArticleDocument) -> Dict[str, Any]:
        """Serialize article and ensure preview field is populated."""
        body = article.model_dump(mode='json')
        body["content_preview"] = cls._build_content_preview(body.get("content"))
        return body

    # ──────────────────────────────────────────
    #  Create
    # ──────────────────────────────────────────

    async def index_article(self, article: ArticleDocument, doc_id: Optional[str] = None) -> str:
        """
        Index a single article.

        Args:
            article: Article document
            doc_id: Optional document ID, auto-generated by ES if not provided

        Returns:
            Document ID
        """
        client = await self._get_client()
        body = self._build_article_body(article)

        kwargs: Dict[str, Any] = {
            "index": ARTICLE_INDEX_NAME,
            "body": body,
        }
        if doc_id:
            kwargs["id"] = doc_id

        result = await client.index(**kwargs)
        return result["_id"]

    async def bulk_index_articles(self, articles: List[ArticleDocument],
                                  doc_ids: Optional[List[str]] = None) -> int:
        """
        Bulk index articles.

        Args:
            articles: Article list
            doc_ids: Optional document ID list, length must match articles

        Returns:
            Number of successfully indexed documents
        """
        if not articles:
            return 0

        client = await self._get_client()
        actions = []
        for i, article in enumerate(articles):
            action = {
                "_index": ARTICLE_INDEX_NAME,
                "_source": self._build_article_body(article),
            }
            if doc_ids and i < len(doc_ids) and doc_ids[i]:
                action["_id"] = doc_ids[i]
            actions.append(action)

        success, errors = await es_helpers.async_bulk(client, actions, raise_on_error=False)
        if errors:
            logger.warning(f"Bulk index completed with {len(errors)} errors: {errors[:3]}")
        return success

    @staticmethod
    def bulk_index_articles_sync(articles: List[ArticleDocument],
                                 doc_ids: Optional[List[str]] = None) -> int:
        """Synchronous version: Bulk index articles."""
        if not articles:
            return 0
        client = get_es_connection_sync()
        actions = []
        for i, article in enumerate(articles):
            action = {
                "_index": ARTICLE_INDEX_NAME,
                "_source": ArticleEsService._build_article_body(article),
            }
            if doc_ids and i < len(doc_ids) and doc_ids[i]:
                action["_id"] = doc_ids[i]
            actions.append(action)
        success, errors = es_helpers.bulk(client, actions, raise_on_error=False)
        if errors:
            logger.warning(f"Bulk index completed with {len(errors)} errors: {errors[:3]}")
        return success

    # ──────────────────────────────────────────
    #  Read
    # ──────────────────────────────────────────

    async def get_article(self, doc_id: str) -> Optional[ArticleDetailResponse]:
        """
        Get article by document ID.

        Args:
            doc_id: ES document ID

        Returns:
            Article search result item, returns None if not found
        """
        client = await self._get_client()
        try:
            result = await client.get(index=ARTICLE_INDEX_NAME, id=doc_id)
            source = result["_source"]
            return ArticleDetailResponse(doc_id=result["_id"], **source)
        except Exception:
            logger.debug(f"Article not found: {doc_id}")
            return None

    # ──────────────────────────────────────────
    #  Update
    # ──────────────────────────────────────────

    async def update_article(self, doc_id: str, updates: Dict[str, Any]) -> bool:
        """
        Partially update article fields.

        Args:
            doc_id: ES document ID
            updates: Dictionary of fields to update

        Returns:
            Whether successful
        """
        client = await self._get_client()
        try:
            updates = dict(updates)
            if "content" in updates:
                updates["content_preview"] = self._build_content_preview(updates.get("content"))
            await client.update(
                index=ARTICLE_INDEX_NAME,
                id=doc_id,
                body={"doc": updates},
            )
            return True
        except Exception as e:
            logger.error(f"Failed to update article {doc_id}: {e}")
            return False

    # ──────────────────────────────────────────
    #  Delete
    # ──────────────────────────────────────────

    async def delete_article(self, doc_id: str) -> bool:
        """
        Delete article.

        Args:
            doc_id: ES document ID

        Returns:
            Whether successful
        """
        client = await self._get_client()
        try:
            await client.delete(index=ARTICLE_INDEX_NAME, id=doc_id)
            return True
        except Exception as e:
            logger.error(f"Failed to delete article {doc_id}: {e}")
            return False

    # ──────────────────────────────────────────
    #  Search & Count
    # ──────────────────────────────────────────

    def _build_rule_query(self, rule: Dict[str, Any]) -> Tuple[Optional[Dict[str, Any]], Optional[str]]:
        """Build ES query for a single rule. Handles both SingleRule and MultiRule.
        Returns (query, rule_type) where rule_type is 'include', 'exclude', or None for MultiRule.
        """
        rule_type = rule.get("type", "single")
        keywords = rule.get("keywords")
        nested_rules = rule.get("rules")

        if rule_type == "multi" or nested_rules is not None:
            # MultiRule: build queries for nested SingleRules, combine with internal relation
            internal_relation = rule.get("relation", "or")
            include_queries = []
            exclude_queries = []

            for sub_rule in nested_rules:
                sub_query, sub_rule_type = self._build_rule_query(sub_rule)
                if sub_query is None:
                    continue
                if sub_rule_type == "include":
                    include_queries.append(sub_query)
                elif sub_rule_type == "exclude":
                    exclude_queries.append(sub_query)

            # Build combined query using internal relation
            must_clauses = []
            must_not_clauses = []

            if include_queries:
                if internal_relation == "and":
                    must_clauses.append({"bool": {"must": include_queries}})
                else:
                    must_clauses.append({"bool": {"should": include_queries, "minimum_should_match": 1}})

            if exclude_queries:
                if internal_relation == "and":
                    must_not_clauses.append({"bool": {"must": exclude_queries}})
                else:
                    must_not_clauses.append({"bool": {"should": exclude_queries, "minimum_should_match": 1}})

            bool_query = {}
            if must_clauses:
                bool_query["must"] = must_clauses
            if must_not_clauses:
                bool_query["must_not"] = must_not_clauses

            if bool_query:
                return {"bool": bool_query}, None
            else:
                return None, None
        else:
            # SingleRule
            if not keywords:
                return None, None
            keyword_queries = []
            for kw in keywords:
                keyword_queries.append({"match_phrase": {"title": {"query": kw}}})
                keyword_queries.append({"match_phrase": {"content": {"query": kw}}})
            return {"bool": {"should": keyword_queries, "minimum_should_match": 1}}, rule.get("rule_type")

    @staticmethod
    def _is_rule_group(item: Dict[str, Any]) -> bool:
        """Check whether the item uses ChannelFilterRules group structure."""
        return "type" not in item and "relation" in item and "rules" in item

    def _normalize_rule_groups(
            self,
            filter_rules: Optional[List[Dict[str, Any]]],
    ) -> List[Dict[str, Any]]:
        """Normalize filter rules into a list of top-level rule groups.
        Only supports ChannelFilterRules group format: {"relation": "and"/"or", "rules": [...]}
        """
        if not filter_rules:
            return []

        # Only accept group format
        return [item for item in filter_rules if isinstance(item, dict) and self._is_rule_group(item)]

    def _build_rule_group_query(self, rule_group: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Build ES query for a top-level ChannelFilterRules group."""
        relation = rule_group.get("relation", "or")
        rules = rule_group.get("rules") or []

        include_queries = []
        exclude_queries = []

        for rule in rules:
            rule_query, rule_type = self._build_rule_query(rule)
            if rule_query is None:
                continue

            if rule_type == "include":
                include_queries.append(rule_query)
            elif rule_type == "exclude":
                exclude_queries.append(rule_query)
            else:
                include_queries.append(rule_query)

        must_clauses = []
        must_not_clauses = []

        if include_queries:
            if relation == "and":
                must_clauses.append({"bool": {"must": include_queries}})
            else:
                must_clauses.append({"bool": {"should": include_queries, "minimum_should_match": 1}})

        if exclude_queries:
            if relation == "and":
                must_not_clauses.append({"bool": {"must": exclude_queries}})
            else:
                must_not_clauses.append({"bool": {"should": exclude_queries, "minimum_should_match": 1}})

        bool_query: Dict[str, Any] = {}
        if must_clauses:
            bool_query["must"] = must_clauses
        if must_not_clauses:
            bool_query["must_not"] = must_not_clauses

        if not bool_query:
            return None

        return {"bool": bool_query}

    def _build_count_query(
            self,
            source_ids: Optional[List[str]] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
            include_article_ids: Optional[List[str]] = None,
    ) -> Optional[Dict[str, Any]]:
        """Build count query, returns None if result is definitively 0"""
        must_clauses = []
        must_not_clauses = []
        filter_clauses = []

        if source_ids is not None:
            if not source_ids:
                return None
            filter_clauses.append({"terms": {"source_id": source_ids}})

        if include_article_ids is not None:
            if not include_article_ids:
                return None
            filter_clauses.append({"terms": {"_id": include_article_ids}})

        if filter_rules:
            rule_groups = self._normalize_rule_groups(filter_rules)
            group_queries = []
            for group in rule_groups:
                group_query = self._build_rule_group_query(group)
                if group_query is not None:
                    group_queries.append(group_query)

            if group_queries:
                if len(group_queries) == 1:
                    must_clauses.append(group_queries[0])
                else:
                    must_clauses.append({
                        "bool": {
                            "should": group_queries,
                            "minimum_should_match": 1,
                        }
                    })

        bool_query: Dict[str, Any] = {}
        if must_clauses:
            bool_query["must"] = must_clauses
        if must_not_clauses:
            bool_query["must_not"] = must_not_clauses
        if filter_clauses:
            bool_query["filter"] = filter_clauses

        if bool_query:
            return {"bool": bool_query}
        else:
            return {"match_all": {}}

    async def count_articles(
            self,
            source_ids: Optional[List[str]] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
            include_article_ids: Optional[List[str]] = None,
    ) -> int:
        """
        Count articles, supports source filtering, filter rules, and article ID list inclusion.
        """
        query = self._build_count_query(source_ids, filter_rules, include_article_ids)
        if query is None:
            return 0

        client = await self._get_client()
        response = await client.count(index=ARTICLE_INDEX_NAME, query=query)
        return response["count"]

    async def count_articles_batch(
            self,
            requests: List[Dict[str, Any]]
    ) -> List[int]:
        """
        Batch count articles.
        requests is a list of dictionaries, each containing parameters for count_articles:
        - source_ids
        - filter_rules
        - include_article_ids
        """
        if not requests:
            return []

        client = await self._get_client()
        body = []
        zero_indices = set()

        for i, req in enumerate(requests):
            query = self._build_count_query(
                source_ids=req.get("source_ids"),
                filter_rules=req.get("filter_rules"),
                include_article_ids=req.get("include_article_ids"),
            )
            if query is None:
                zero_indices.add(i)
                # msearch requires valid query even if we know it's zero to maintain order easily
                body.append({"index": ARTICLE_INDEX_NAME})
                body.append({"query": {"match_none": {}}, "size": 0})
            else:
                body.append({"index": ARTICLE_INDEX_NAME})
                body.append({"query": query, "size": 0})

        response = await client.msearch(body=body)

        counts = []
        for i, r in enumerate(response["responses"]):
            if i in zero_indices:
                counts.append(0)
            else:
                total = r["hits"]["total"]
                counts.append(total["value"] if isinstance(total, dict) else total)
        return counts

    async def search_articles(
            self,
            source_ids: Optional[List[str]] = None,
            keyword: Optional[str] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
            page: int = 1,
            page_size: int = 20,
            exclude_article_ids: Optional[List[str]] = None,
    ) -> ArticleSearchPageResponse:
        """
        Search articles, supports source filtering, keyword search, filter rules, highlighting, and pagination.

        Args:
            source_ids: Source ID list filter
            keyword: Search keyword (matches title, content, source ID)
            filter_rules: Channel filter rules list (supports SingleRule and MultiRule groups)
            page: Page number (starts from 1)
            page_size: Page size
            exclude_article_ids: List of article IDs to exclude

        Returns:
            ArticleSearchPageResponse
        """
        client = await self._get_client()

        # Build bool query
        must_clauses = []
        must_not_clauses = []
        filter_clauses = []

        # 1. Source ID filtering
        if source_ids:
            filter_clauses.append({
                "terms": {"source_id": source_ids}
            })

        # 1.5 Exclude specified article IDs
        if exclude_article_ids:
            must_not_clauses.append({
                "terms": {"_id": exclude_article_ids}
            })

        # 2. Keyword search (title + content + source ID)
        if keyword:
            must_clauses.append({
                "bool": {
                    "should": [
                        {"match_phrase": {"title": {"query": keyword, "boost": 3}}},
                        {"match_phrase": {"content": {"query": keyword}}},
                        {"match_phrase": {"source_id": {"query": keyword}}},
                    ],
                    "minimum_should_match": 1,
                }
            })

        # 3. Channel filter rules
        if filter_rules:
            rule_groups = self._normalize_rule_groups(filter_rules)
            group_queries = []
            for group in rule_groups:
                group_query = self._build_rule_group_query(group)
                if group_query is not None:
                    group_queries.append(group_query)

            if group_queries:
                if len(group_queries) == 1:
                    must_clauses.append(group_queries[0])
                else:
                    must_clauses.append({
                        "bool": {
                            "should": group_queries,
                            "minimum_should_match": 1,
                        }
                    })

        # Assemble complete query
        bool_query: Dict[str, Any] = {}
        if must_clauses:
            bool_query["must"] = must_clauses
        if must_not_clauses:
            bool_query["must_not"] = must_not_clauses
        if filter_clauses:
            bool_query["filter"] = filter_clauses

        if bool_query:
            query = {"bool": bool_query}
        else:
            query = {"match_all": {}}

        # Highlighting configuration - only highlight user keyword, not filter_rules keywords
        highlight_config = {}
        if keyword:
            # Use highlight_query to limit highlighting to only the user's keyword
            highlight_query = {
                "bool": {
                    "should": [
                        {"match_phrase": {"title": {"query": keyword}}},
                        {"match_phrase": {"content": {"query": keyword}}},
                    ],
                    "minimum_should_match": 1,
                }
            }
            highlight_config = {
                "pre_tags": ["<em>"],
                "post_tags": ["</em>"],
                "fields": {
                    "title": {"number_of_fragments": 0, "highlight_query": highlight_query},
                    "content": {"fragment_size": 200, "number_of_fragments": 3, "highlight_query": highlight_query,
                                "max_analyzed_offset": 999999},
                },
            }

        # Build request body
        from_offset = (page - 1) * page_size
        body: Dict[str, Any] = {
            "query": query,
            "sort": [{"publish_time": {"order": "desc"}}],
            "from": from_offset,
            "size": page_size,
            "_source": [
                "source_type",
                "source_id",
                "title",
                "content_preview",
                "cover_image",
                "publish_time",
                "source_url",
                "create_time",
                "update_time",
            ],
        }
        if highlight_config:
            body["highlight"] = highlight_config

        # Execute search
        response = await client.search(index=ARTICLE_INDEX_NAME, body=body)

        # Parse results
        total = response["hits"]["total"]
        if isinstance(total, dict):
            total_count = total["value"]
        else:
            total_count = total

        items = []
        for hit in response["hits"]["hits"]:
            source = dict(hit["_source"])
            highlight = hit.get("highlight")
            source["content"] = source.pop("content_preview", "")

            item = ArticleSearchResultItem(
                doc_id=hit["_id"],
                score=hit.get("_score"),
                highlight=highlight,
                **source,
            )
            items.append(item)

        return ArticleSearchPageResponse(
            data=items,
            total=total_count,
            page=page,
            page_size=page_size,
        )

    def match_article_ids_sync(
            self,
            article_ids: List[str],
            source_ids: Optional[List[str]] = None,
            filter_rules: Optional[List[Dict[str, Any]]] = None,
    ) -> List[str]:
        """Return the subset of `article_ids` that match the given source/filter
        predicate. Used by the knowledge-sync worker to evaluate sub-channel
        rules against freshly-indexed articles.
        """
        if not article_ids:
            return []
        query = self._build_count_query(
            source_ids=source_ids,
            filter_rules=filter_rules,
            include_article_ids=article_ids,
        )
        if query is None:
            return []
        client = get_es_connection_sync()
        body = {
            "query": query,
            "_source": False,
            "size": len(article_ids),
        }
        response = client.search(index=ARTICLE_INDEX_NAME, body=body)
        return [hit["_id"] for hit in response.get("hits", {}).get("hits", [])]

    @staticmethod
    def get_source_latest_article_time_sync(source_id: str) -> Optional[str]:
        """Get source's latest article update time (synchronous method)"""
        client = get_es_connection_sync()
        body = {
            "size": 1,
            "query": {
                "term": {"source_id": source_id}
            },
            "sort": [{"create_time": {"order": "desc"}}],
            "_source": ["create_time"],
        }
        response = client.search(index=ARTICLE_INDEX_NAME, body=body)
        hits = response["hits"]["hits"]
        if hits:
            return hits[0]["_source"]["create_time"]
        return None
