"""F003: Extend group table for user group management.

Adds visibility column. Changes group_name unique constraint from global
to (tenant_id, group_name) composite unique.

Revision ID: f003_user_group
Revises: f001_multi_tenant
Create Date: 2026-04-12
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'f003_user_group'
down_revision: Union[str, Sequence[str], None] = 'f001_multi_tenant'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add visibility column and change unique constraint on group table."""

    # 1. Add visibility column (default 'public' backfills existing rows)
    op.add_column(
        'group',
        sa.Column('visibility', sa.String(16), nullable=False,
                  server_default='public',
                  comment='Visibility: public/private'),
    )

    # 2. Drop old unique index on group_name (auto-generated by SQLModel)
    try:
        op.drop_index('ix_group_group_name', table_name='group')
    except Exception:
        pass  # Index may not exist or have a different name

    # 3. Add composite unique constraint (tenant_id + group_name)
    op.create_unique_constraint(
        'uk_tenant_group_name', 'group', ['tenant_id', 'group_name'],
    )


def downgrade() -> None:
    """Reverse: remove composite unique, restore global unique, drop visibility."""

    op.drop_constraint('uk_tenant_group_name', 'group', type_='unique')

    # Restore global unique index (best-effort, may fail if duplicate names exist)
    try:
        op.create_index('ix_group_group_name', 'group', ['group_name'], unique=True)
    except Exception:
        pass

    op.drop_column('group', 'visibility')
